"""
Train BC from batched data format.

This script trains BC from the batch format generated by generate_bc_data_parallel.py.
All I/O is on local disk (/data/caihy) to avoid NFS bottleneck.

Key features:
- Loads data from batch files on GPU03 local disk
- Saves checkpoints to GPU03 local disk
- No evaluation during training (user has separate evaluation script)
- Memory-efficient batch loading

Usage:
    python train_bc_from_batches.py --data_dir /data/caihy/bc_data_1M_hard_xxx --log_dir /data/caihy/bc_training
"""

import os
_gpu_id = os.environ.get("CUDA_VISIBLE_DEVICES", "0")
os.environ["CUDA_VISIBLE_DEVICES"] = _gpu_id
os.environ["SDL_VIDEODRIVER"] = "offscreen"
os.environ["PYOPENGL_PLATFORM"] = "egl"
if "DISPLAY" in os.environ:
    del os.environ["DISPLAY"]

import argparse
import numpy as np
from pathlib import Path
import sys
import time
import json
import torch
import gc
import psutil
import gymnasium
sys.modules['gym'] = gymnasium


def get_memory_usage():
    """Get current memory usage in MB."""
    process = psutil.Process(os.getpid())
    return process.memory_info().rss / 1024 / 1024


class BatchedDataLoader:
    """
    Data loader for batched format.
    Loads one batch file at a time and CACHES it for multiple samples.
    This is CRITICAL for performance - loading npz files is slow!
    """
    
    def __init__(self, data_dir: str, batch_size: int = 1024, device: str = "auto", samples_per_file: int = 20):
        self.data_dir = Path(data_dir)
        self.batches_dir = self.data_dir / "batches"
        self.batch_size = batch_size
        self.samples_per_file = samples_per_file  # How many batches to sample before loading new file
        
        if device == "auto":
            self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        else:
            self.device = torch.device(device)
        
        # Load metadata if exists, otherwise infer from files
        metadata_path = self.data_dir / "metadata.json"
        if metadata_path.exists():
            with open(metadata_path, 'r') as f:
                self.metadata = json.load(f)
            self.transitions_per_file = self.metadata.get('batch_size', 20480)
        else:
            self.metadata = {}
            self.transitions_per_file = 20480  # Default
        
        # List batch files dynamically
        self.batch_files = sorted(list(self.batches_dir.glob("batch_*.npz")))
        self.num_batch_files = len(self.batch_files)
        if self.num_batch_files == 0:
            raise ValueError(f"No batch files found in {self.batches_dir}")
        self.total_transitions = self.num_batch_files * self.transitions_per_file
        
        # Caching for performance
        self.cached_data = None
        self.cached_file_idx = -1
        self.samples_from_current_file = 0
        
        print(f"BatchedDataLoader initialized:")
        print(f"  Data dir: {self.data_dir}")
        print(f"  Batch files: {self.num_batch_files}")
        print(f"  Transitions per file: {self.transitions_per_file}")
        print(f"  Total transitions: {self.total_transitions}")
        print(f"  Training batch size: {self.batch_size}")
        print(f"  Samples per file (cache reuse): {self.samples_per_file}")
        print(f"  Device: {self.device}")
    
    def _load_new_file(self):
        """Load a random batch file into cache."""
        file_idx = np.random.randint(0, self.num_batch_files)
        data = np.load(self.batch_files[file_idx])
        
        self.cached_data = {
            'obs_image': data['obs_image'],
            'obs_state': data['obs_state'],
            'action': data['action'],
            'size': data['size'] if 'size' in data else len(data['obs_image']),
        }
        self.cached_file_idx = file_idx
        self.samples_from_current_file = 0
    
    def sample(self):
        """
        Sample a batch of transitions from cached data.
        Reloads a new file every `samples_per_file` samples.
        """
        # Check if we need to load a new file
        if self.cached_data is None or self.samples_from_current_file >= self.samples_per_file:
            self._load_new_file()
        
        self.samples_from_current_file += 1
        
        # Sample indices from cached file
        file_size = self.cached_data['size']
        indices = np.random.choice(file_size, size=self.batch_size, replace=True)
        
        # Extract samples
        obs_image = torch.as_tensor(
            self.cached_data['obs_image'][indices], 
            device=self.device, dtype=torch.float32
        )
        obs_state = torch.as_tensor(
            self.cached_data['obs_state'][indices], 
            device=self.device, dtype=torch.float32
        )
        actions = torch.as_tensor(
            self.cached_data['action'][indices], 
            device=self.device, dtype=torch.float32
        )
        
        # Combine observations as dict
        observations = {'image': obs_image, 'state': obs_state}
        
        return observations, actions


def main():
    parser = argparse.ArgumentParser(description="Train BC from batched data")
    parser.add_argument("--data_dir", type=str, required=True,
                        help="Directory containing batched data (on GPU03 local disk)")
    parser.add_argument("--log_dir", type=str, default="",
                        help="Directory for logs and checkpoints (on GPU03 local disk)")
    parser.add_argument("--bc_training_steps", type=int, default=10000,
                        help="Total training steps")
    parser.add_argument("--batch_size", type=int, default=1024,
                        help="Batch size for training")
    parser.add_argument("--learning_rate", type=float, default=1e-4,
                        help="Learning rate")
    parser.add_argument("--save_freq", type=int, default=1000,
                        help="Checkpoint save frequency")
    parser.add_argument("--log_freq", type=int, default=100,
                        help="Logging frequency")
    parser.add_argument("--toy", action="store_true",
                        help="Toy mode for testing")
    parser.add_argument("--seed", type=int, default=0,
                        help="Random seed")
    parser.add_argument("--ckpt", type=str, default="",
                        help="Path to initial checkpoint")
    parser.add_argument("--wandb", action="store_true",
                        help="Enable wandb logging")
    parser.add_argument("--wandb_project", type=str, default="bc-hard-seeds",
                        help="Wandb project name")
    parser.add_argument("--wandb_team", type=str, default="victorique",
                        help="Wandb team name")
    parser.add_argument("--exp_name", type=str, default="bc-1M",
                        help="Experiment name")
    args = parser.parse_args()
    
    # Toy mode
    if args.toy:
        print("=" * 80, flush=True)
        print("TOY MODE ENABLED", flush=True)
        print("=" * 80, flush=True)
        args.bc_training_steps = 20
        args.batch_size = 256
        args.save_freq = 5
        args.log_freq = 5
    
    # Set seeds
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    
    # Validate paths
    data_dir = Path(args.data_dir)
    if not data_dir.exists():
        print(f"ERROR: Data directory not found: {data_dir}")
        sys.exit(1)
    
    # Setup log directory (on GPU03 local disk!)
    if args.log_dir:
        log_dir = Path(args.log_dir)
    else:
        log_dir = Path("/data/caihy/bc_training")
    
    from pvp.utils.utils import get_time_str
    import uuid
    trial_name = f"{args.exp_name}_{get_time_str()}_{uuid.uuid4().hex[:8]}"
    trial_dir = log_dir / trial_name
    trial_dir.mkdir(parents=True, exist_ok=True)
    
    print("=" * 80, flush=True)
    print("BC Training from Batched Data", flush=True)
    print("=" * 80, flush=True)
    print(f"Data directory: {data_dir}", flush=True)
    print(f"Log directory: {trial_dir}", flush=True)
    print(f"Training steps: {args.bc_training_steps}", flush=True)
    print(f"Batch size: {args.batch_size}", flush=True)
    print(f"Save freq: {args.save_freq}", flush=True)
    print(f"Initial memory: {get_memory_usage():.1f} MB", flush=True)
    print("=" * 80, flush=True)
    
    # Create data loader
    print("\n[1] Creating data loader...", flush=True)
    data_loader = BatchedDataLoader(str(data_dir), batch_size=args.batch_size)
    print(f"    Memory after data loader: {get_memory_usage():.1f} MB", flush=True)
    
    # Test data loading
    print("\n[2] Testing data loading...", flush=True)
    obs, actions = data_loader.sample()
    print(f"    obs['image'] shape: {obs['image'].shape}", flush=True)
    print(f"    obs['state'] shape: {obs['state'].shape}", flush=True)
    print(f"    actions shape: {actions.shape}", flush=True)
    print(f"    Batch size correct: {actions.shape[0] == args.batch_size}", flush=True)
    print(f"    Memory after sample: {get_memory_usage():.1f} MB", flush=True)
    
    # Create model
    print("\n[3] Creating BC model...", flush=True)
    from pvp.sb3.td3.td3 import TD3
    from pvp.sb3.td3.policies import TD3Policy
    from pvp.sb3.sac.our_features_extractor import OurFeaturesExtractorCNN as OurFeaturesExtractor
    
    # Create a simple dummy observation/action space without loading full metadrive
    import gymnasium as gym
    
    # Match the observation space from data
    obs_space = gym.spaces.Dict({
        'image': gym.spaces.Box(low=0, high=1, shape=(84, 84, 3, 3), dtype=np.float32),
        'state': gym.spaces.Box(low=-np.inf, high=np.inf, shape=(19,), dtype=np.float32),
    })
    action_space = gym.spaces.Box(low=-1, high=1, shape=(2,), dtype=np.float32)
    
    # Create a minimal dummy env wrapper
    class DummyEnv(gym.Env):
        def __init__(self):
            super().__init__()
            self.observation_space = obs_space
            self.action_space = action_space
            self.num_envs = 1
            self.metadata = {'render.modes': []}
        def reset(self, seed=None, options=None):
            return {'image': np.zeros((84, 84, 3, 3), dtype=np.float32), 'state': np.zeros(19, dtype=np.float32)}, {}
        def step(self, action):
            return {'image': np.zeros((84, 84, 3, 3), dtype=np.float32), 'state': np.zeros(19, dtype=np.float32)}, 0.0, False, False, {}
        def render(self):
            pass
        def close(self):
            pass
    
    dummy_env = DummyEnv()
    
    policy_kwargs = dict(
        features_extractor_class=OurFeaturesExtractor,
        features_extractor_kwargs=dict(features_dim=275),
        share_features_extractor=False,
        net_arch=[256,]
    )
    
    model = TD3(
        policy=TD3Policy,
        env=dummy_env,
        learning_rate=args.learning_rate,
        buffer_size=1000,
        batch_size=args.batch_size,
        tau=0.005,
        gamma=0.99,
        train_freq=1,
        gradient_steps=1,
        policy_delay=2,
        tensorboard_log=str(trial_dir),
        verbose=2,
        seed=args.seed,
        device="auto",
        policy_kwargs=policy_kwargs,
        use_td3_bc=False,
        bc_loss_weight=1.0,
    )
    
    dummy_env.close()
    print(f"    Model device: {model.device}", flush=True)
    print(f"    Memory after model: {get_memory_usage():.1f} MB", flush=True)
    
    # Load initial checkpoint
    print("\n[4] Loading initial checkpoint...", flush=True)
    script_dir = Path(os.path.dirname(os.path.abspath(__file__)))
    if args.ckpt:
        ckpt_path = Path(args.ckpt)
    else:
        ckpt_path = script_dir / "domainAexpertBC.zip"
    
    if ckpt_path.exists():
        print(f"    Loading from: {ckpt_path}", flush=True)
        from pvp.sb3.common.save_util import load_from_zip_file
        data, params, pytorch_variables = load_from_zip_file(ckpt_path, device=model.device, print_system_info=False)
        model.set_parameters(params, exact_match=False, device=model.device)
        print(f"    Checkpoint loaded!", flush=True)
    else:
        print(f"    WARNING: Checkpoint not found: {ckpt_path}", flush=True)
    
    print(f"    Memory after checkpoint: {get_memory_usage():.1f} MB", flush=True)
    
    # Initialize wandb
    wandb_run = None
    if args.wandb:
        print("\n[5] Initializing wandb...", flush=True)
        try:
            import wandb as wandb_module
            wandb_run = wandb_module.init(
                project=args.wandb_project,
                entity=args.wandb_team,
                name=trial_name,
                config=vars(args),
            )
            print("    Wandb initialized!", flush=True)
        except Exception as e:
            print(f"    WARNING: Failed to initialize wandb: {e}", flush=True)
            args.wandb = False
    
    # Training loop
    print("\n" + "=" * 80, flush=True)
    print("Starting BC Training Loop", flush=True)
    print("=" * 80, flush=True)
    
    from pvp.sb3.common.utils import polyak_update
    
    start_time = time.time()
    total_loss = 0
    memory_samples = []
    log_freq = args.log_freq
    
    # Accumulators for averaging
    loss_acc = []
    steering_loss_acc = []
    accel_loss_acc = []
    
    for step in range(1, args.bc_training_steps + 1):
        # Sample batch
        obs, actions = data_loader.sample()
        
        # Forward pass
        model.actor.train()
        predicted_actions = model.actor(obs)
        
        # BC loss (total)
        bc_loss = torch.nn.functional.mse_loss(predicted_actions, actions)
        
        # Per-dimension losses
        bc_loss_steering = torch.nn.functional.mse_loss(predicted_actions[:, 0], actions[:, 0])
        bc_loss_accel = torch.nn.functional.mse_loss(predicted_actions[:, 1], actions[:, 1])
        
        # Backward pass
        model.actor.optimizer.zero_grad()
        bc_loss.backward()
        
        # Gradient norm (before clipping)
        grad_norm = 0.0
        for p in model.actor.parameters():
            if p.grad is not None:
                grad_norm += p.grad.data.norm(2).item() ** 2
        grad_norm = grad_norm ** 0.5
        
        model.actor.optimizer.step()
        
        # Update target network
        if step % model.policy_delay == 0:
            polyak_update(model.actor.parameters(), model.actor_target.parameters(), model.tau)
        
        # Accumulate for averaging
        loss_acc.append(bc_loss.item())
        steering_loss_acc.append(bc_loss_steering.item())
        accel_loss_acc.append(bc_loss_accel.item())
        model._n_updates += 1
        
        # Memory tracking
        current_memory = get_memory_usage()
        memory_samples.append(current_memory)
        
        # Logging
        if step % log_freq == 0 or step == 1:
            elapsed = time.time() - start_time
            rate = step / elapsed
            eta_seconds = (args.bc_training_steps - step) / rate if rate > 0 else 0
            eta_hours = eta_seconds / 3600
            
            avg_loss = np.mean(loss_acc[-log_freq:]) if loss_acc else 0
            avg_steering_loss = np.mean(steering_loss_acc[-log_freq:]) if steering_loss_acc else 0
            avg_accel_loss = np.mean(accel_loss_acc[-log_freq:]) if accel_loss_acc else 0
            
            log_msg = f"[{step}/{args.bc_training_steps}] Loss: {avg_loss:.4f} (steer: {avg_steering_loss:.4f}, accel: {avg_accel_loss:.4f}), Mem: {current_memory:.0f}MB, Rate: {rate:.1f}/s, ETA: {eta_hours:.1f}h"
            print(log_msg, flush=True)
            
            if args.wandb and wandb_run:
                # Compute detailed action statistics
                with torch.no_grad():
                    data_steering = actions[:, 0]
                    data_accel = actions[:, 1]
                    policy_steering = predicted_actions[:, 0]
                    policy_accel = predicted_actions[:, 1]
                    action_diff_l2 = torch.norm(predicted_actions - actions, dim=1).mean().item()
                
                wandb_run.log({
                    # Loss metrics
                    'train/bc_loss': avg_loss,
                    'train/bc_loss_steering': avg_steering_loss,
                    'train/bc_loss_accel': avg_accel_loss,
                    'train/grad_norm': grad_norm,
                    
                    # Data action statistics
                    'train/data_mean_steering': data_steering.mean().item(),
                    'train/data_mean_steering_abs': torch.abs(data_steering).mean().item(),
                    'train/data_mean_accel': data_accel.mean().item(),
                    'train/data_mean_accel_abs': torch.abs(data_accel).mean().item(),
                    'train/data_std_steering': data_steering.std().item(),
                    'train/data_std_accel': data_accel.std().item(),
                    
                    # Policy action statistics
                    'train/policy_mean_steering': policy_steering.mean().item(),
                    'train/policy_mean_steering_abs': torch.abs(policy_steering).mean().item(),
                    'train/policy_mean_accel': policy_accel.mean().item(),
                    'train/policy_mean_accel_abs': torch.abs(policy_accel).mean().item(),
                    'train/policy_std_steering': policy_steering.std().item(),
                    'train/policy_std_accel': policy_accel.std().item(),
                    
                    # Action difference
                    'train/action_diff_l2': action_diff_l2,
                    
                    # Training stats
                    'train/n_updates': model._n_updates,
                    'train/learning_rate': args.learning_rate,
                    'train/memory_mb': current_memory,
                    'train/step': step,
                    'train/rate_per_sec': rate,
                    'train/eta_hours': eta_hours,
                }, step=step)
        
        # Save checkpoint
        if step % args.save_freq == 0:
            ckpt_path = trial_dir / f"bc_step_{step:06d}.zip"
            model.save(str(ckpt_path))
            print(f"    [SAVE] Checkpoint saved: {ckpt_path}", flush=True)
            
            # Verify checkpoint is on local disk
            if str(ckpt_path).startswith("/data/"):
                print(f"    [OK] Checkpoint on local disk (GPU03)", flush=True)
            else:
                print(f"    [WARNING] Checkpoint NOT on local disk!", flush=True)
    
    # Final save
    final_path = trial_dir / "bc_final.zip"
    model.save(str(final_path))
    print(f"\n[FINAL] Saved: {final_path}", flush=True)
    
    # Memory leak check
    print("\n" + "=" * 80, flush=True)
    print("Memory Leak Check", flush=True)
    print("=" * 80, flush=True)
    
    if len(memory_samples) > 10:
        first_10 = np.mean(memory_samples[:10])
        last_10 = np.mean(memory_samples[-10:])
        memory_growth = last_10 - first_10
        
        print(f"    First 10 steps avg: {first_10:.1f} MB", flush=True)
        print(f"    Last 10 steps avg: {last_10:.1f} MB", flush=True)
        print(f"    Memory growth: {memory_growth:.1f} MB", flush=True)
        
        if memory_growth > 500:
            print(f"    [WARNING] Possible memory leak detected!", flush=True)
        else:
            print(f"    [OK] No significant memory leak", flush=True)
    
    # Summary
    print("\n" + "=" * 80, flush=True)
    print("Training Summary", flush=True)
    print("=" * 80, flush=True)
    print(f"    Total steps: {args.bc_training_steps}", flush=True)
    print(f"    Total updates: {model._n_updates}", flush=True)
    print(f"    Training time: {(time.time() - start_time)/60:.1f} min", flush=True)
    print(f"    Final memory: {get_memory_usage():.1f} MB", flush=True)
    print(f"    Checkpoints saved to: {trial_dir}", flush=True)
    print("=" * 80, flush=True)
    
    # Verify all checkpoints
    print("\n[VERIFY] Checking saved checkpoints...", flush=True)
    saved_ckpts = list(trial_dir.glob("*.zip"))
    print(f"    Found {len(saved_ckpts)} checkpoints", flush=True)
    for ckpt in saved_ckpts[:5]:
        print(f"      - {ckpt.name} ({os.path.getsize(ckpt)/1024/1024:.1f} MB)", flush=True)
    
    if args.wandb and wandb_run:
        wandb_run.finish()


if __name__ == "__main__":
    main()
