"""
Train BC from batched data format.

This script trains BC from the batch format generated by generate_bc_data_parallel.py.
All I/O is on local disk (/data/caihy) to avoid NFS bottleneck.

Key features:
- Loads data from batch files on GPU03 local disk
- Saves checkpoints to GPU03 local disk
- Online rollout collection during training (logs rollout/* metrics to wandb)
- Memory-efficient batch loading

Usage:
    python train_bc_from_batches.py --data_dir /data/caihy/bc_data_1M_hard_xxx --log_dir /data/caihy/bc_training
"""

# CRITICAL: Set gym -> gymnasium alias BEFORE any other imports
# This must be first to ensure metadrive and other packages use gymnasium
import sys
import gymnasium
import gymnasium.spaces
sys.modules['gym'] = gymnasium
sys.modules['gym.spaces'] = gymnasium.spaces
gymnasium.spaces.space = gymnasium.spaces  # metadrive uses gym.spaces.space.Space

import os
_gpu_id = os.environ.get("CUDA_VISIBLE_DEVICES", "0")
os.environ["CUDA_VISIBLE_DEVICES"] = _gpu_id
os.environ["SDL_VIDEODRIVER"] = "offscreen"
os.environ["PYOPENGL_PLATFORM"] = "egl"
if "DISPLAY" in os.environ:
    del os.environ["DISPLAY"]

import argparse
import numpy as np
from pathlib import Path
import time
import json
import torch
import gc
import psutil
import hashlib
from collections import deque, defaultdict


# Top 200 hardest scenarios for the lidar PPO expert (in [0, 1000) range)
# MUST match generate_bc_data_sequential.py EXACTLY
HARD_200_SEEDS = [
    751, 849, 61, 963, 160, 257, 678, 491, 892, 410,
    403, 35, 473, 725, 171, 536, 376, 192, 755, 169,
    947, 586, 59, 535, 418, 694, 424, 452, 64, 100,
    548, 973, 180, 369, 313, 488, 557, 821, 318, 91,
    481, 969, 230, 120, 646, 942, 73, 806, 549, 315,
    799, 816, 740, 781, 382, 738, 609, 765, 930, 932,
    534, 747, 183, 401, 300, 692, 41, 367, 804, 959,
    400, 984, 492, 46, 389, 354, 706, 448, 435, 92,
    277, 543, 986, 903, 413, 239, 90, 484, 837, 819,
    791, 454, 459, 758, 85, 168, 194, 567, 680, 205,
    126, 373, 297, 208, 44, 794, 525, 533, 57, 142,
    12, 762, 844, 598, 685, 368, 832, 946, 966, 178,
    250, 572, 9, 825, 584, 11, 728, 269, 232, 898,
    668, 374, 29, 760, 238, 5, 653, 524, 950, 611,
    888, 243, 185, 215, 319, 934, 72, 923, 345, 236,
    119, 248, 364, 553, 985, 199, 207, 392, 352, 355,
    214, 894, 70, 847, 156, 336, 221, 965, 184, 735,
    620, 305, 944, 718, 226, 773, 530, 987, 891, 261,
    859, 394, 188, 951, 622, 769, 340, 225, 344, 540,
    640, 975, 114, 727, 68, 310, 265, 273, 726, 42,
]


class SimpleMonitor:
    """
    Simplified Monitor that wraps an env and tracks episode statistics.
    Avoids compatibility issues with gym/gymnasium.
    """
    def __init__(self, env):
        self.env = env
        self.rewards = []
        self.episode_infos = defaultdict(list)
        self.t_start = time.time()
        self._last_info = {}
        
    @property
    def observation_space(self):
        return self.env.observation_space
    
    @property
    def action_space(self):
        return self.env.action_space
    
    @property
    def unwrapped(self):
        return self.env.unwrapped if hasattr(self.env, 'unwrapped') else self.env
    
    def reset(self, **kwargs):
        self.rewards = []
        self.episode_infos = defaultdict(list)
        return self.env.reset(**kwargs)
    
    def step(self, action):
        obs, reward, done, info = self.env.step(action)
        self.rewards.append(reward)
        self._last_info = info
        
        # Track all info keys
        for key, val in info.items():
            if isinstance(val, (int, float, np.number)):
                self.episode_infos[key].append(val)
        
        if done:
            ep_rew = sum(self.rewards)
            ep_len = len(self.rewards)
            ep_info = {"r": round(ep_rew, 6), "l": ep_len, "t": round(time.time() - self.t_start, 6)}
            
            # Add final info values
            for key, val in info.items():
                if isinstance(val, (int, float, np.number, bool)):
                    ep_info[key] = val
                    # Also add episode mean for accumulated values
                    if key in self.episode_infos and len(self.episode_infos[key]) > 0:
                        ep_info["ep_{}".format(key)] = np.mean(self.episode_infos[key])
            
            info["episode"] = ep_info
        
        return obs, reward, done, info
    
    def close(self):
        self.env.close()


def create_rollout_env(daytime="06:10"):
    """
    Create a rollout environment with Monitor wrapper for online evaluation.
    Uses the same config as data generation (generate_bc_data_sequential.py).
    
    Returns:
        env: Environment with Monitor wrapper
        seeds_hash: Hash of the seeds for verification
        actual_env_config: Actual config values read from the environment
    """
    # Use FakeHumanEnv like generate_bc_data_sequential.py (no manual control needed)
    from pvp.experiments.metadrive.egpo.fakehuman_env import FakeHumanEnv
    from pvp.sb3.common.monitor import Monitor  # Use the original Monitor like train_ppo_metadrive.py
    from metadrive.component.sensors.rgb_camera import RGBCamera
    
    sensor_size = (84, 84)
    
    # Same config as generate_bc_data_sequential.py
    env_config = dict(
        image_observation=True,
        vehicle_config=dict(image_source="rgb_camera"),
        sensors={"rgb_camera": (RGBCamera, *sensor_size)},
        horizon=1500,
        # Safety settings - match data generation
        crash_vehicle_done=False,
        crash_object_done=False,
        crash_vehicle_penalty=5.0,
        crash_object_penalty=5.0,
        out_of_road_penalty=5.0,
        # Reward settings
        driving_reward=1.0,
        speed_reward=0.1,
        use_lateral_reward=False,
        # Other settings
        daytime=daytime,
        use_render=False,
        disable_expert=True,  # IMPORTANT: Use OUR policy's action, not expert's!
        start_seed=0,
        num_scenarios=1000,
        # DO NOT set traffic_density - use env default (0.06)
    )
    
    # Create wrapper that cycles through hard seeds
    class HardSeedEnv(FakeHumanEnv):
        """Wrapper that cycles through HARD_200_SEEDS on reset."""
        def __init__(self, config):
            super().__init__(config)
            self.hard_seeds = HARD_200_SEEDS
            self.seed_idx = 0
            self.seeds_used = []
        
        def reset(self, **kwargs):
            # Select next seed from hard seeds (cycling)
            seed = self.hard_seeds[self.seed_idx % len(self.hard_seeds)]
            self.seed_idx += 1
            kwargs['seed'] = seed
            self.seeds_used.append(seed)
            return super().reset(**kwargs)
    
    # Create env and wrap with Monitor (same as train_ppo_metadrive.py)
    # gym/gymnasium compatibility is handled by sys.modules['gym'] = gymnasium at top of file
    env = HardSeedEnv(config=env_config)
    env = Monitor(env=env)
    
    # Compute seeds hash for verification
    seeds_str = ','.join(map(str, sorted(HARD_200_SEEDS)))
    seeds_hash = hashlib.md5(seeds_str.encode()).hexdigest()[:16]
    
    # Read actual config from env after initialization
    actual_env_config = {
        'traffic_density': env.unwrapped.config.get('traffic_density', 0.06),
        'daytime': env.unwrapped.config.get('daytime', daytime),
        'out_of_road_penalty': env.unwrapped.config.get('out_of_road_penalty', 5.0),
        'crash_vehicle_penalty': env.unwrapped.config.get('crash_vehicle_penalty', 5.0),
        'crash_object_penalty': env.unwrapped.config.get('crash_object_penalty', 5.0),
        'driving_reward': env.unwrapped.config.get('driving_reward', 1.0),
        'speed_reward': env.unwrapped.config.get('speed_reward', 0.1),
        'horizon': env.unwrapped.config.get('horizon', 1500),
    }
    
    return env, seeds_hash, actual_env_config


def safe_mean(arr):
    """Compute mean of a list, returning 0 if empty."""
    return np.mean(arr) if len(arr) > 0 else 0.0


def get_memory_usage():
    """Get current memory usage in MB."""
    process = psutil.Process(os.getpid())
    return process.memory_info().rss / 1024 / 1024


class BatchedDataLoader:
    """
    Data loader for batched format.
    Loads one batch file at a time and CACHES it for multiple samples.
    This is CRITICAL for performance - loading npz files is slow!
    """
    
    def __init__(self, data_dir: str, batch_size: int = 1024, device: str = "auto", samples_per_file: int = 20):
        self.data_dir = Path(data_dir)
        self.batches_dir = self.data_dir / "batches"
        self.batch_size = batch_size
        self.samples_per_file = samples_per_file  # How many batches to sample before loading new file
        
        if device == "auto":
            self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        else:
            self.device = torch.device(device)
        
        # Load metadata if exists, otherwise infer from files
        metadata_path = self.data_dir / "metadata.json"
        if metadata_path.exists():
            with open(metadata_path, 'r') as f:
                self.metadata = json.load(f)
            self.transitions_per_file = self.metadata.get('batch_size', 20480)
        else:
            self.metadata = {}
            self.transitions_per_file = 20480  # Default
        
        # List batch files dynamically
        self.batch_files = sorted(list(self.batches_dir.glob("batch_*.npz")))
        self.num_batch_files = len(self.batch_files)
        if self.num_batch_files == 0:
            raise ValueError(f"No batch files found in {self.batches_dir}")
        self.total_transitions = self.num_batch_files * self.transitions_per_file
        
        # Caching for performance
        self.cached_data = None
        self.cached_file_idx = -1
        self.samples_from_current_file = 0
        
        print(f"BatchedDataLoader initialized:")
        print(f"  Data dir: {self.data_dir}")
        print(f"  Batch files: {self.num_batch_files}")
        print(f"  Transitions per file: {self.transitions_per_file}")
        print(f"  Total transitions: {self.total_transitions}")
        print(f"  Training batch size: {self.batch_size}")
        print(f"  Samples per file (cache reuse): {self.samples_per_file}")
        print(f"  Device: {self.device}")
    
    def _load_new_file(self):
        """Load a random batch file into cache."""
        file_idx = np.random.randint(0, self.num_batch_files)
        data = np.load(self.batch_files[file_idx])
        
        self.cached_data = {
            'obs_image': data['obs_image'],
            'obs_state': data['obs_state'],
            'action': data['action'],
            'size': data['size'] if 'size' in data else len(data['obs_image']),
        }
        self.cached_file_idx = file_idx
        self.samples_from_current_file = 0
    
    def sample(self):
        """
        Sample a batch of transitions from cached data.
        Reloads a new file every `samples_per_file` samples.
        """
        # Check if we need to load a new file
        if self.cached_data is None or self.samples_from_current_file >= self.samples_per_file:
            self._load_new_file()
        
        self.samples_from_current_file += 1
        
        # Sample indices from cached file
        file_size = self.cached_data['size']
        indices = np.random.choice(file_size, size=self.batch_size, replace=True)
        
        # Extract samples
        obs_image = torch.as_tensor(
            self.cached_data['obs_image'][indices], 
            device=self.device, dtype=torch.float32
        )
        obs_state = torch.as_tensor(
            self.cached_data['obs_state'][indices], 
            device=self.device, dtype=torch.float32
        )
        actions = torch.as_tensor(
            self.cached_data['action'][indices], 
            device=self.device, dtype=torch.float32
        )
        
        # Combine observations as dict
        observations = {'image': obs_image, 'state': obs_state}
        
        return observations, actions


def main():
    parser = argparse.ArgumentParser(description="Train BC from batched data")
    parser.add_argument("--data_dir", type=str, required=True,
                        help="Directory containing batched data (on GPU03 local disk)")
    parser.add_argument("--log_dir", type=str, default="",
                        help="Directory for logs and checkpoints (on GPU03 local disk)")
    parser.add_argument("--bc_training_steps", type=int, default=10000,
                        help="Total training steps")
    parser.add_argument("--batch_size", type=int, default=1024,
                        help="Batch size for training")
    parser.add_argument("--learning_rate", type=float, default=1e-4,
                        help="Learning rate")
    parser.add_argument("--save_freq", type=int, default=1000,
                        help="Checkpoint save frequency")
    parser.add_argument("--log_freq", type=int, default=100,
                        help="Logging frequency")
    parser.add_argument("--toy", action="store_true",
                        help="Toy mode for testing")
    parser.add_argument("--seed", type=int, default=0,
                        help="Random seed")
    parser.add_argument("--ckpt", type=str, default="",
                        help="Path to initial checkpoint (for resuming training)")
    parser.add_argument("--start_step", type=int, default=0,
                        help="Starting step (for resuming training, e.g., 40000 to continue from 40K)")
    parser.add_argument("--wandb", action="store_true",
                        help="Enable wandb logging")
    parser.add_argument("--wandb_project", type=str, default="bc-hard-seeds",
                        help="Wandb project name")
    parser.add_argument("--wandb_team", type=str, default="victorique",
                        help="Wandb team name")
    parser.add_argument("--exp_name", type=str, default="bc-1M",
                        help="Experiment name")
    parser.add_argument("--daytime", type=str, default="06:10",
                        help="Daytime for rollout env (should match data generation)")
    parser.add_argument("--rollout_log_freq", type=int, default=100,
                        help="How often to log rollout metrics (in training steps)")
    parser.add_argument("--rollout_step_freq", type=int, default=1,
                        help="Do rollout every N training steps (1=every step, 5=every 5 steps)")
    parser.add_argument("--no_rollout", action="store_true",
                        help="Disable online rollout collection")
    args = parser.parse_args()
    
    # Toy mode
    if args.toy:
        print("=" * 80, flush=True)
        print("TOY MODE ENABLED", flush=True)
        print("=" * 80, flush=True)
        args.bc_training_steps = 20
        args.batch_size = 256
        args.save_freq = 5
        args.log_freq = 5
    
    # Set seeds
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    
    # Validate paths
    data_dir = Path(args.data_dir)
    if not data_dir.exists():
        print(f"ERROR: Data directory not found: {data_dir}")
        sys.exit(1)
    
    # Setup log directory (on GPU03 local disk!)
    if args.log_dir:
        log_dir = Path(args.log_dir)
    else:
        log_dir = Path("/data/caihy/bc_training")
    
    from pvp.utils.utils import get_time_str
    import uuid
    trial_name = f"{args.exp_name}_{get_time_str()}_{uuid.uuid4().hex[:8]}"
    trial_dir = log_dir / trial_name
    trial_dir.mkdir(parents=True, exist_ok=True)
    
    print("=" * 80, flush=True)
    print("BC Training from Batched Data", flush=True)
    print("=" * 80, flush=True)
    print(f"Data directory: {data_dir}", flush=True)
    print(f"Log directory: {trial_dir}", flush=True)
    print(f"Training steps: {args.bc_training_steps}", flush=True)
    print(f"Batch size: {args.batch_size}", flush=True)
    print(f"Save freq: {args.save_freq}", flush=True)
    print(f"Initial memory: {get_memory_usage():.1f} MB", flush=True)
    print("=" * 80, flush=True)
    
    # Create data loader
    print("\n[1] Creating data loader...", flush=True)
    data_loader = BatchedDataLoader(str(data_dir), batch_size=args.batch_size)
    print(f"    Memory after data loader: {get_memory_usage():.1f} MB", flush=True)
    
    # Test data loading
    print("\n[2] Testing data loading...", flush=True)
    obs, actions = data_loader.sample()
    print(f"    obs['image'] shape: {obs['image'].shape}", flush=True)
    print(f"    obs['state'] shape: {obs['state'].shape}", flush=True)
    print(f"    actions shape: {actions.shape}", flush=True)
    print(f"    Batch size correct: {actions.shape[0] == args.batch_size}", flush=True)
    print(f"    Memory after sample: {get_memory_usage():.1f} MB", flush=True)
    
    # Create model
    print("\n[3] Creating BC model...", flush=True)
    from pvp.sb3.td3.td3 import TD3
    from pvp.sb3.td3.policies import TD3Policy
    from pvp.sb3.sac.our_features_extractor import OurFeaturesExtractorCNN as OurFeaturesExtractor
    
    # Create a simple dummy observation/action space without loading full metadrive
    import gymnasium as gym
    
    # Match the observation space from data
    obs_space = gym.spaces.Dict({
        'image': gym.spaces.Box(low=0, high=1, shape=(84, 84, 3, 3), dtype=np.float32),
        'state': gym.spaces.Box(low=-np.inf, high=np.inf, shape=(19,), dtype=np.float32),
    })
    action_space = gym.spaces.Box(low=-1, high=1, shape=(2,), dtype=np.float32)
    
    # Create a minimal dummy env wrapper
    class DummyEnv(gym.Env):
        def __init__(self):
            super().__init__()
            self.observation_space = obs_space
            self.action_space = action_space
            self.num_envs = 1
            self.metadata = {'render.modes': []}
        def reset(self, seed=None, options=None):
            return {'image': np.zeros((84, 84, 3, 3), dtype=np.float32), 'state': np.zeros(19, dtype=np.float32)}, {}
        def step(self, action):
            return {'image': np.zeros((84, 84, 3, 3), dtype=np.float32), 'state': np.zeros(19, dtype=np.float32)}, 0.0, False, False, {}
        def render(self):
            pass
        def close(self):
            pass
    
    dummy_env = DummyEnv()
    
    policy_kwargs = dict(
        features_extractor_class=OurFeaturesExtractor,
        features_extractor_kwargs=dict(features_dim=275),
        share_features_extractor=False,
        net_arch=[256,]
    )
    
    model = TD3(
        policy=TD3Policy,
        env=dummy_env,
        learning_rate=args.learning_rate,
        buffer_size=1000,
        batch_size=args.batch_size,
        tau=0.005,
        gamma=0.99,
        train_freq=1,
        gradient_steps=1,
        policy_delay=2,
        tensorboard_log=str(trial_dir),
        verbose=2,
        seed=args.seed,
        device="auto",
        policy_kwargs=policy_kwargs,
        use_td3_bc=False,
        bc_loss_weight=1.0,
    )
    
    dummy_env.close()
    print(f"    Model device: {model.device}", flush=True)
    print(f"    Memory after model: {get_memory_usage():.1f} MB", flush=True)
    
    # Load initial checkpoint
    print("\n[4] Loading initial checkpoint...", flush=True)
    script_dir = Path(os.path.dirname(os.path.abspath(__file__)))
    if args.ckpt:
        ckpt_path = Path(args.ckpt)
    else:
        ckpt_path = script_dir / "domainAexpertBC.zip"
    
    if ckpt_path.exists():
        print(f"    Loading from: {ckpt_path}", flush=True)
        from pvp.sb3.common.save_util import load_from_zip_file
        data, params, pytorch_variables = load_from_zip_file(ckpt_path, device=model.device, print_system_info=False)
        model.set_parameters(params, exact_match=False, device=model.device)
        print(f"    Checkpoint loaded!", flush=True)
    else:
        print(f"    WARNING: Checkpoint not found: {ckpt_path}", flush=True)
    
    print(f"    Memory after checkpoint: {get_memory_usage():.1f} MB", flush=True)
    
    # Initialize wandb
    wandb_run = None
    if args.wandb:
        print("\n[5] Initializing wandb...", flush=True)
        try:
            import wandb as wandb_module
            wandb_run = wandb_module.init(
                project=args.wandb_project,
                entity=args.wandb_team,
                name=trial_name,
                config=vars(args),
            )
            print("    Wandb initialized!", flush=True)
        except Exception as e:
            print(f"    WARNING: Failed to initialize wandb: {e}", flush=True)
            args.wandb = False
    
    # Create rollout environment for online evaluation
    rollout_env = None
    rollout_obs = None
    ep_info_buffer = deque(maxlen=100)  # Store recent episode infos
    ep_extended_buffer = deque(maxlen=100)  # Store extended metrics (success_no_bad, etc.)
    rollout_seeds_hash = None
    actual_rollout_config = None
    
    # Rollout episode-level tracking (reset on episode end)
    rollout_episode_count = 0
    rollout_step_in_episode = 0
    rollout_had_crash_vehicle = False
    rollout_had_crash_object = False
    rollout_had_out_of_road = False
    rollout_had_bad_event = False
    rollout_arrive_dest = False
    rollout_route_completion = 0.0
    rollout_total_crash_penalty = 0.0
    rollout_total_out_of_road_penalty = 0.0
    rollout_total_velocity = 0.0
    rollout_min_vehicle_distance = float('inf')
    rollout_close_encounters = 0
    rollout_safe_passes = 0
    rollout_dangerous_close = 0
    rollout_current_seed = None
    
    if not args.no_rollout:
        print("\n[6] Creating rollout environment...", flush=True)
        try:
            rollout_env, rollout_seeds_hash, actual_rollout_config = create_rollout_env(daytime=args.daytime)
            # Monitor.reset() returns just obs, not (obs, info) tuple
            rollout_obs = rollout_env.reset()
            print(f"    Rollout env created!", flush=True)
            print(f"    Seeds hash: {rollout_seeds_hash}", flush=True)
            print(f"    Actual env config:", flush=True)
            for k, v in actual_rollout_config.items():
                print(f"      {k}: {v}", flush=True)
            
            # Log env config to wandb
            if args.wandb and wandb_run:
                daytime_numeric = int(args.daytime.replace(":", "")) if args.daytime else 0
                env_cfg_metrics = {
                    'env_cfg/traffic_density': actual_rollout_config['traffic_density'],
                    'env_cfg/daytime_numeric': daytime_numeric,
                    'env_cfg/out_of_road_penalty': actual_rollout_config['out_of_road_penalty'],
                    'env_cfg/crash_vehicle_penalty': actual_rollout_config['crash_vehicle_penalty'],
                    'env_cfg/crash_object_penalty': actual_rollout_config['crash_object_penalty'],
                    'env_cfg/driving_reward': actual_rollout_config['driving_reward'],
                    'env_cfg/speed_reward': actual_rollout_config['speed_reward'],
                    'env_cfg/horizon': actual_rollout_config['horizon'],
                    'env_cfg/num_seeds': len(HARD_200_SEEDS),
                    'env_cfg/seeds_hash_numeric': int(rollout_seeds_hash[:8], 16) % 1000000,
                }
                wandb_run.log(env_cfg_metrics)
                wandb_run.summary['seeds_hash'] = rollout_seeds_hash
                wandb_run.summary['daytime'] = args.daytime
                wandb_run.summary['traffic_density'] = actual_rollout_config['traffic_density']
                print(f"    Logged env_cfg to wandb!", flush=True)
        except Exception as e:
            print(f"    WARNING: Failed to create rollout env: {e}", flush=True)
            import traceback
            traceback.print_exc()
            rollout_env = None
    else:
        print("\n[6] Rollout collection disabled (--no_rollout)", flush=True)
    
    # Training loop
    print("\n" + "=" * 80, flush=True)
    print("Starting BC Training Loop", flush=True)
    print("=" * 80, flush=True)
    
    from pvp.sb3.common.utils import polyak_update
    
    start_time = time.time()
    total_loss = 0
    memory_samples = []
    log_freq = args.log_freq
    start_step = args.start_step
    total_steps = args.bc_training_steps
    
    if start_step > 0:
        print(f"\n[7] RESUMING from step {start_step}...", flush=True)
        print(f"    Training steps: {start_step + 1} to {total_steps}", flush=True)
    
    # Accumulators for averaging
    loss_acc = []
    steering_loss_acc = []
    accel_loss_acc = []
    
    for step in range(start_step + 1, total_steps + 1):
        # Sample batch
        obs, actions = data_loader.sample()
        
        # Forward pass
        model.actor.train()
        predicted_actions = model.actor(obs)
        
        # BC loss (total)
        bc_loss = torch.nn.functional.mse_loss(predicted_actions, actions)
        
        # Per-dimension losses
        bc_loss_steering = torch.nn.functional.mse_loss(predicted_actions[:, 0], actions[:, 0])
        bc_loss_accel = torch.nn.functional.mse_loss(predicted_actions[:, 1], actions[:, 1])
        
        # Backward pass
        model.actor.optimizer.zero_grad()
        bc_loss.backward()
        
        # Gradient norm (before clipping)
        grad_norm = 0.0
        for p in model.actor.parameters():
            if p.grad is not None:
                grad_norm += p.grad.data.norm(2).item() ** 2
        grad_norm = grad_norm ** 0.5
        
        model.actor.optimizer.step()
        
        # Update target network
        if step % model.policy_delay == 0:
            polyak_update(model.actor.parameters(), model.actor_target.parameters(), model.tau)
        
        # Accumulate for averaging
        loss_acc.append(bc_loss.item())
        steering_loss_acc.append(bc_loss_steering.item())
        accel_loss_acc.append(bc_loss_accel.item())
        model._n_updates += 1
        
        # ============ ONLINE ROLLOUT COLLECTION (ENHANCED) ============
        # Collect one step of rollout data using current policy
        # Only do rollout every N steps for speedup
        if rollout_env is not None and rollout_obs is not None and step % args.rollout_step_freq == 0:
            rollout_step_in_episode += 1
            
            with torch.no_grad():
                # Convert observation to tensor (reuse buffer if possible)
                rollout_obs_tensor = {
                    'image': torch.as_tensor(rollout_obs['image'], device=model.device, dtype=torch.float32).unsqueeze(0),
                    'state': torch.as_tensor(rollout_obs['state'], device=model.device, dtype=torch.float32).unsqueeze(0),
                }
                # Get action from policy (no need for eval()/train() inside no_grad())
                policy_action = model.actor(rollout_obs_tensor).cpu().numpy().squeeze()
            
            # Step environment with policy action
            new_obs, reward, done, info = rollout_env.step(policy_action)
            
            # Get current seed on first step of episode
            if rollout_step_in_episode == 1:
                rollout_current_seed = info.get('env_seed', None)
            
            # === VERIFICATION: Print action comparison for first 5 episodes ===
            if rollout_episode_count < 5 and rollout_step_in_episode == 1:
                # Get actions from info
                executed_action = info.get('action', None)  # Action actually used by env
                
                # Verify policy_action == executed_action (proves self.actor output is used)
                if executed_action is not None:
                    exec_arr = np.array(executed_action) if hasattr(executed_action, '__iter__') else executed_action
                    policy_matches_executed = np.allclose(policy_action, exec_arr, atol=0.001)
                else:
                    policy_matches_executed = 'N/A'
                
                print(f"[Rollout Verify] Ep={rollout_episode_count+1} seed={rollout_current_seed} "
                      f"daytime={actual_rollout_config.get('daytime')} density={actual_rollout_config.get('traffic_density')}", flush=True)
                print(f"[Rollout Verify] self.actor output: {[f'{x:.4f}' for x in policy_action.tolist()]}", flush=True)
                print(f"[Rollout Verify] env executed action: {[f'{x:.4f}' for x in list(executed_action)] if executed_action is not None else 'N/A'}", flush=True)
                print(f"[Rollout Verify] ✓ CONFIRMED: BC policy action is used by env: {policy_matches_executed}", flush=True)
                print(f"[Rollout Verify] (disable_expert=True, so no lidar PPO expert involved)", flush=True)
            
            # === STEP-BY-STEP METRIC TRACKING ===
            # Track velocity
            velocity = info.get('velocity', 0.0)
            if isinstance(velocity, (list, np.ndarray)):
                velocity = np.linalg.norm(velocity)
            rollout_total_velocity += velocity
            
            # Track crash events
            if info.get('crash_vehicle', False):
                rollout_had_crash_vehicle = True
                rollout_total_crash_penalty += 5.0  # crash_vehicle_penalty
            if info.get('crash_object', False):
                rollout_had_crash_object = True
                rollout_total_crash_penalty += 5.0  # crash_object_penalty
            if info.get('out_of_road', False):
                rollout_had_out_of_road = True
                rollout_total_out_of_road_penalty += 5.0
            
            # Track bad event
            if rollout_had_crash_vehicle or rollout_had_crash_object or rollout_had_out_of_road:
                rollout_had_bad_event = True
            
            # Track success
            if info.get('arrive_dest', False):
                rollout_arrive_dest = True
            
            # Track route completion
            rollout_route_completion = max(rollout_route_completion, info.get('route_completion', 0.0))
            
            # Track traffic proximity (close encounters < 5m)
            min_dist = info.get('min_vehicle_distance', float('inf'))
            if min_dist < float('inf'):
                rollout_min_vehicle_distance = min(rollout_min_vehicle_distance, min_dist)
            if min_dist < 5.0:  # Close encounter threshold
                rollout_close_encounters += 1
                step_crash = info.get('crash_vehicle', False) or info.get('crash_object', False)
                if step_crash:
                    rollout_dangerous_close += 1
                else:
                    rollout_safe_passes += 1
            
            # === EPISODE END ===
            if done:
                rollout_episode_count += 1
                
                # Compute extended metrics
                success_no_bad = rollout_arrive_dest and not rollout_had_bad_event
                rc_no_bad = rollout_route_completion if not rollout_had_bad_event else 0.0
                avg_velocity = rollout_total_velocity / rollout_step_in_episode if rollout_step_in_episode > 0 else 0.0
                safe_pass_rate = rollout_safe_passes / rollout_close_encounters if rollout_close_encounters > 0 else 1.0
                close_enc_crash_rate = rollout_dangerous_close / rollout_close_encounters if rollout_close_encounters > 0 else 0.0
                
                # Store basic ep_info from Monitor
                if 'episode' in info:
                    ep_info_buffer.append(info['episode'])
                
                # Store extended metrics
                ep_extended = {
                    'seed': rollout_current_seed,
                    'success_no_bad': float(success_no_bad),
                    'success_rate': float(rollout_arrive_dest),
                    'route_completion': rollout_route_completion,
                    'route_completion_no_bad': rc_no_bad,
                    'crash_vehicle_rate': float(rollout_had_crash_vehicle),
                    'crash_object_rate': float(rollout_had_crash_object),
                    'out_of_road_rate': float(rollout_had_out_of_road),
                    'any_bad_event_rate': float(rollout_had_bad_event),
                    'crash_penalty': rollout_total_crash_penalty,
                    'out_of_road_penalty': rollout_total_out_of_road_penalty,
                    'avg_velocity': avg_velocity,
                    'min_vehicle_distance': rollout_min_vehicle_distance if rollout_min_vehicle_distance < float('inf') else -1,
                    'close_encounters': rollout_close_encounters,
                    'safe_passes': rollout_safe_passes,
                    'dangerous_close': rollout_dangerous_close,
                    'safe_pass_rate': safe_pass_rate,
                    'close_enc_crash_rate': close_enc_crash_rate,
                    'episode_length': rollout_step_in_episode,
                }
                ep_extended_buffer.append(ep_extended)
                
                # Reset episode tracking
                rollout_step_in_episode = 0
                rollout_had_crash_vehicle = False
                rollout_had_crash_object = False
                rollout_had_out_of_road = False
                rollout_had_bad_event = False
                rollout_arrive_dest = False
                rollout_route_completion = 0.0
                rollout_total_crash_penalty = 0.0
                rollout_total_out_of_road_penalty = 0.0
                rollout_total_velocity = 0.0
                rollout_min_vehicle_distance = float('inf')
                rollout_close_encounters = 0
                rollout_safe_passes = 0
                rollout_dangerous_close = 0
                rollout_current_seed = None
                
                # Reset for next episode (Monitor.reset() returns just obs)
                rollout_obs = rollout_env.reset()
            else:
                rollout_obs = new_obs
        else:
            pass
        # ====================================================
        
        # Memory tracking
        current_memory = get_memory_usage()
        memory_samples.append(current_memory)
        
        # Logging
        if step % log_freq == 0 or step == start_step + 1:
            elapsed = time.time() - start_time
            steps_done = step - start_step
            rate = steps_done / elapsed if elapsed > 0 else 0
            steps_remaining = total_steps - step
            eta_seconds = steps_remaining / rate if rate > 0 else 0
            eta_hours = eta_seconds / 3600
            
            avg_loss = np.mean(loss_acc[-log_freq:]) if loss_acc else 0
            avg_steering_loss = np.mean(steering_loss_acc[-log_freq:]) if steering_loss_acc else 0
            avg_accel_loss = np.mean(accel_loss_acc[-log_freq:]) if accel_loss_acc else 0
            
            log_msg = f"[{step}/{total_steps}] Loss: {avg_loss:.4f} (steer: {avg_steering_loss:.4f}, accel: {avg_accel_loss:.4f}), Mem: {current_memory:.0f}MB, Rate: {rate:.1f}/s, ETA: {eta_hours:.1f}h"
            print(log_msg, flush=True)
            
            if args.wandb and wandb_run:
                # Compute detailed action statistics
                with torch.no_grad():
                    data_steering = actions[:, 0]
                    data_accel = actions[:, 1]
                    policy_steering = predicted_actions[:, 0]
                    policy_accel = predicted_actions[:, 1]
                    action_diff_l2 = torch.norm(predicted_actions - actions, dim=1).mean().item()
                
                log_dict = {
                    # Loss metrics
                    'train/bc_loss': avg_loss,
                    'train/bc_loss_steering': avg_steering_loss,
                    'train/bc_loss_accel': avg_accel_loss,
                    'train/grad_norm': grad_norm,
                    
                    # Data action statistics
                    'train/data_mean_steering': data_steering.mean().item(),
                    'train/data_mean_steering_abs': torch.abs(data_steering).mean().item(),
                    'train/data_mean_accel': data_accel.mean().item(),
                    'train/data_mean_accel_abs': torch.abs(data_accel).mean().item(),
                    'train/data_std_steering': data_steering.std().item(),
                    'train/data_std_accel': data_accel.std().item(),
                    
                    # Policy action statistics
                    'train/policy_mean_steering': policy_steering.mean().item(),
                    'train/policy_mean_steering_abs': torch.abs(policy_steering).mean().item(),
                    'train/policy_mean_accel': policy_accel.mean().item(),
                    'train/policy_mean_accel_abs': torch.abs(policy_accel).mean().item(),
                    'train/policy_std_steering': policy_steering.std().item(),
                    'train/policy_std_accel': policy_accel.std().item(),
                    
                    # Action difference
                    'train/action_diff_l2': action_diff_l2,
                    
                    # Training stats
                    'train/n_updates': model._n_updates,
                    'train/learning_rate': args.learning_rate,
                    'train/memory_mb': current_memory,
                    'train/step': step,
                    'train/rate_per_sec': rate,
                    'train/eta_hours': eta_hours,
                }
                
                # ============ ROLLOUT METRICS (ENHANCED) ============
                # Log rollout metrics from ep_info_buffer + ep_extended_buffer
                if len(ep_info_buffer) > 0 and step % args.rollout_log_freq == 0:
                    # Core metrics from Monitor
                    log_dict['rollout/ep_rew_mean'] = safe_mean([ep_info["r"] for ep_info in ep_info_buffer])
                    log_dict['rollout/ep_len_mean'] = safe_mean([ep_info["l"] for ep_info in ep_info_buffer])
                    
                    # Log ALL environment-specific metrics from Monitor (same as _dump_logs)
                    first_ep_info = ep_info_buffer[-1]
                    for k, v in first_ep_info.items():
                        if k not in ["r", "l"] and type(v) is not str:
                            try:
                                log_dict["rollout/{}_mean".format(k)] = safe_mean(
                                    [ep_info[k] for ep_info in ep_info_buffer if k in ep_info]
                                )
                            except (TypeError, ValueError, KeyError):
                                pass
                    
                    # Also log "total_*" as sums
                    for k, v in first_ep_info.items():
                        if k.startswith("total"):
                            log_dict["rollout/{}_sum".format(k)] = ep_info_buffer[-1].get(k, 0)
                    
                    # ======== EXTENDED METRICS from ep_extended_buffer ========
                    if len(ep_extended_buffer) > 0:
                        # Success metrics
                        log_dict['rollout/success_no_bad'] = safe_mean([ep['success_no_bad'] for ep in ep_extended_buffer])
                        log_dict['rollout/success_rate'] = safe_mean([ep['success_rate'] for ep in ep_extended_buffer])
                        
                        # Route completion metrics
                        log_dict['rollout/route_completion_no_bad'] = safe_mean([ep['route_completion_no_bad'] for ep in ep_extended_buffer])
                        
                        # Safety metrics
                        log_dict['rollout/crash_vehicle_rate'] = safe_mean([ep['crash_vehicle_rate'] for ep in ep_extended_buffer])
                        log_dict['rollout/crash_object_rate'] = safe_mean([ep['crash_object_rate'] for ep in ep_extended_buffer])
                        log_dict['rollout/out_of_road_rate'] = safe_mean([ep['out_of_road_rate'] for ep in ep_extended_buffer])
                        log_dict['rollout/any_bad_event_rate'] = safe_mean([ep['any_bad_event_rate'] for ep in ep_extended_buffer])
                        
                        # Reward decomposition
                        log_dict['rollout/crash_penalty_mean'] = safe_mean([ep['crash_penalty'] for ep in ep_extended_buffer])
                        log_dict['rollout/out_of_road_penalty_mean'] = safe_mean([ep['out_of_road_penalty'] for ep in ep_extended_buffer])
                        log_dict['rollout/avg_velocity_mean'] = safe_mean([ep['avg_velocity'] for ep in ep_extended_buffer])
                        
                        # Traffic proximity
                        min_dists = [ep['min_vehicle_distance'] for ep in ep_extended_buffer if ep['min_vehicle_distance'] > 0]
                        log_dict['rollout/min_vehicle_distance'] = safe_mean(min_dists) if min_dists else -1
                        log_dict['rollout/close_encounters_mean'] = safe_mean([ep['close_encounters'] for ep in ep_extended_buffer])
                        log_dict['rollout/safe_pass_rate'] = safe_mean([ep['safe_pass_rate'] for ep in ep_extended_buffer])
                        log_dict['rollout/close_enc_crash_rate'] = safe_mean([ep['close_enc_crash_rate'] for ep in ep_extended_buffer])
                        
                        # Difficulty segment analysis (if enough episodes)
                        if len(ep_extended_buffer) >= 5:
                            # Sort by seed to analyze by difficulty (lower seeds = harder in HARD_200_SEEDS)
                            sorted_eps = sorted([ep for ep in ep_extended_buffer if ep['seed'] is not None], 
                                               key=lambda x: HARD_200_SEEDS.index(x['seed']) if x['seed'] in HARD_200_SEEDS else 999)
                            if len(sorted_eps) >= 5:
                                num_per_seg = len(sorted_eps) // 5
                                segments = ['hardest', 'hard', 'medium', 'easy', 'easiest']
                                for seg_idx, seg_name in enumerate(segments):
                                    start_idx = seg_idx * num_per_seg
                                    end_idx = min(start_idx + num_per_seg, len(sorted_eps))
                                    if start_idx < len(sorted_eps):
                                        seg_eps = sorted_eps[start_idx:end_idx]
                                        log_dict[f'rollout/segment_{seg_name}_success'] = safe_mean([ep['success_rate'] for ep in seg_eps])
                                        log_dict[f'rollout/segment_{seg_name}_crash'] = safe_mean([ep['crash_vehicle_rate'] for ep in seg_eps])
                    # ===========================================================
                    
                    # Print rollout summary (enhanced)
                    if step % (args.rollout_log_freq * 5) == 0:
                        succ_no_bad = log_dict.get('rollout/success_no_bad', 0)
                        rc_no_bad = log_dict.get('rollout/route_completion_no_bad', 0)
                        crash = log_dict.get('rollout/crash_vehicle_rate', 0)
                        out_road = log_dict.get('rollout/out_of_road_rate', 0)
                        crash_pen = log_dict.get('rollout/crash_penalty_mean', 0)
                        safe_pass = log_dict.get('rollout/safe_pass_rate', 0)
                        print(f"    [Rollout] Ep={len(ep_extended_buffer)} R={log_dict.get('rollout/ep_rew_mean', 0):.1f} "
                              f"SuccNoBad={succ_no_bad:.0%} RCNoBad={rc_no_bad:.0%} "
                              f"Crash={crash:.0%} OoR={out_road:.0%} CrashPen={crash_pen:.1f} SafePass={safe_pass:.0%}", flush=True)
                # =========================================
                
                wandb_run.log(log_dict, step=step)
        
        # Save checkpoint
        if step % args.save_freq == 0:
            ckpt_path = trial_dir / f"bc_step_{step:06d}.zip"
            model.save(str(ckpt_path))
            print(f"    [SAVE] Checkpoint saved: {ckpt_path}", flush=True)
            
            # Verify checkpoint is on local disk
            if str(ckpt_path).startswith("/data/"):
                print(f"    [OK] Checkpoint on local disk (GPU03)", flush=True)
            else:
                print(f"    [WARNING] Checkpoint NOT on local disk!", flush=True)
    
    # Final save
    final_path = trial_dir / "bc_final.zip"
    model.save(str(final_path))
    print(f"\n[FINAL] Saved: {final_path}", flush=True)
    
    # Memory leak check
    print("\n" + "=" * 80, flush=True)
    print("Memory Leak Check", flush=True)
    print("=" * 80, flush=True)
    
    if len(memory_samples) > 10:
        first_10 = np.mean(memory_samples[:10])
        last_10 = np.mean(memory_samples[-10:])
        memory_growth = last_10 - first_10
        
        print(f"    First 10 steps avg: {first_10:.1f} MB", flush=True)
        print(f"    Last 10 steps avg: {last_10:.1f} MB", flush=True)
        print(f"    Memory growth: {memory_growth:.1f} MB", flush=True)
        
        if memory_growth > 500:
            print(f"    [WARNING] Possible memory leak detected!", flush=True)
        else:
            print(f"    [OK] No significant memory leak", flush=True)
    
    # Summary
    print("\n" + "=" * 80, flush=True)
    print("Training Summary", flush=True)
    print("=" * 80, flush=True)
    print(f"    Start step: {start_step}", flush=True)
    print(f"    End step: {total_steps}", flush=True)
    print(f"    Steps trained this run: {total_steps - start_step}", flush=True)
    print(f"    Total updates: {model._n_updates}", flush=True)
    print(f"    Training time: {(time.time() - start_time)/60:.1f} min", flush=True)
    print(f"    Final memory: {get_memory_usage():.1f} MB", flush=True)
    print(f"    Checkpoints saved to: {trial_dir}", flush=True)
    print("=" * 80, flush=True)
    
    # Verify all checkpoints
    print("\n[VERIFY] Checking saved checkpoints...", flush=True)
    saved_ckpts = list(trial_dir.glob("*.zip"))
    print(f"    Found {len(saved_ckpts)} checkpoints", flush=True)
    for ckpt in saved_ckpts[:5]:
        print(f"      - {ckpt.name} ({os.path.getsize(ckpt)/1024/1024:.1f} MB)", flush=True)
    
    # Cleanup rollout env
    if rollout_env is not None:
        print("\n[CLEANUP] Closing rollout environment...", flush=True)
        rollout_env.close()
        print("    Rollout env closed!", flush=True)
    
    if args.wandb and wandb_run:
        wandb_run.finish()


if __name__ == "__main__":
    main()
