"""
Train BC from batched data format.

This script trains BC from the batch format generated by generate_bc_data_parallel.py.
All I/O is on local disk (/data/caihy) to avoid NFS bottleneck.

Key features:
- Loads data from batch files on GPU03 local disk
- Saves checkpoints to GPU03 local disk
- Online rollout collection during training (logs rollout/* metrics to wandb)
- Memory-efficient batch loading

Usage:
    python train_bc_from_batches.py --data_dir /data/caihy/bc_data_1M_hard_xxx --log_dir /data/caihy/bc_training
"""

# CRITICAL: Set gym -> gymnasium alias BEFORE any other imports
# This must be first to ensure metadrive and other packages use gymnasium
import sys
import gymnasium
import gymnasium.spaces
sys.modules['gym'] = gymnasium
sys.modules['gym.spaces'] = gymnasium.spaces
gymnasium.spaces.space = gymnasium.spaces  # metadrive uses gym.spaces.space.Space

import os
_gpu_id = os.environ.get("CUDA_VISIBLE_DEVICES", "0")
os.environ["CUDA_VISIBLE_DEVICES"] = _gpu_id
os.environ["SDL_VIDEODRIVER"] = "offscreen"
os.environ["PYOPENGL_PLATFORM"] = "egl"
if "DISPLAY" in os.environ:
    del os.environ["DISPLAY"]

import argparse
import numpy as np
from pathlib import Path
import time
import json
import torch
import gc
import psutil
import hashlib
from collections import deque, defaultdict

# CuPy for GPU image acceleration (optional)
_cupy_available = False
try:
    import cupy as cp
    from torch.utils.dlpack import from_dlpack
    _cupy_available = True
except ImportError:
    pass  # cupy not installed, will use CPU path


# Top 200 hardest scenarios for the lidar PPO expert (in [0, 1000) range)
# MUST match generate_bc_data_sequential.py EXACTLY
HARD_200_SEEDS = [
    751, 849, 61, 963, 160, 257, 678, 491, 892, 410,
    403, 35, 473, 725, 171, 536, 376, 192, 755, 169,
    947, 586, 59, 535, 418, 694, 424, 452, 64, 100,
    548, 973, 180, 369, 313, 488, 557, 821, 318, 91,
    481, 969, 230, 120, 646, 942, 73, 806, 549, 315,
    799, 816, 740, 781, 382, 738, 609, 765, 930, 932,
    534, 747, 183, 401, 300, 692, 41, 367, 804, 959,
    400, 984, 492, 46, 389, 354, 706, 448, 435, 92,
    277, 543, 986, 903, 413, 239, 90, 484, 837, 819,
    791, 454, 459, 758, 85, 168, 194, 567, 680, 205,
    126, 373, 297, 208, 44, 794, 525, 533, 57, 142,
    12, 762, 844, 598, 685, 368, 832, 946, 966, 178,
    250, 572, 9, 825, 584, 11, 728, 269, 232, 898,
    668, 374, 29, 760, 238, 5, 653, 524, 950, 611,
    888, 243, 185, 215, 319, 934, 72, 923, 345, 236,
    119, 248, 364, 553, 985, 199, 207, 392, 352, 355,
    214, 894, 70, 847, 156, 336, 221, 965, 184, 735,
    620, 305, 944, 718, 226, 773, 530, 987, 891, 261,
    859, 394, 188, 951, 622, 769, 340, 225, 344, 540,
    640, 975, 114, 727, 68, 310, 265, 273, 726, 42,
]


class SimpleMonitor:
    """
    Simplified Monitor that wraps an env and tracks episode statistics.
    Avoids compatibility issues with gym/gymnasium.
    """
    def __init__(self, env):
        self.env = env
        self.rewards = []
        self.episode_infos = defaultdict(list)
        self.t_start = time.time()
        self._last_info = {}
        
    @property
    def observation_space(self):
        return self.env.observation_space
    
    @property
    def action_space(self):
        return self.env.action_space
    
    @property
    def unwrapped(self):
        return self.env.unwrapped if hasattr(self.env, 'unwrapped') else self.env
    
    def reset(self, **kwargs):
        self.rewards = []
        self.episode_infos = defaultdict(list)
        return self.env.reset(**kwargs)
    
    def step(self, action):
        obs, reward, done, info = self.env.step(action)
        self.rewards.append(reward)
        self._last_info = info
        
        # Track all info keys
        for key, val in info.items():
            if isinstance(val, (int, float, np.number)):
                self.episode_infos[key].append(val)
        
        if done:
            ep_rew = sum(self.rewards)
            ep_len = len(self.rewards)
            ep_info = {"r": round(ep_rew, 6), "l": ep_len, "t": round(time.time() - self.t_start, 6)}
            
            # Add final info values
            for key, val in info.items():
                if isinstance(val, (int, float, np.number, bool)):
                    ep_info[key] = val
                    # Also add episode mean for accumulated values
                    if key in self.episode_infos and len(self.episode_infos[key]) > 0:
                        ep_info["ep_{}".format(key)] = np.mean(self.episode_infos[key])
            
            info["episode"] = ep_info
        
        return obs, reward, done, info
    
    def close(self):
        self.env.close()


def _make_rollout_env_subprocess(env_id, daytime, hard_seeds):
    """
    Factory function for creating a single rollout environment.
    This is defined at module level to be pickle-friendly for SubprocVecEnv.
    """
    from pvp.experiments.metadrive.egpo.fakehuman_env import FakeHumanEnv
    from pvp.sb3.common.monitor import Monitor
    from metadrive.component.sensors.rgb_camera import RGBCamera
    
    sensor_size = (84, 84)
    
    env_config = dict(
        image_observation=True,
        image_on_cuda=False,  # Disabled for SubprocVecEnv
        vehicle_config=dict(image_source="rgb_camera"),
        sensors={"rgb_camera": (RGBCamera, *sensor_size)},
        horizon=1500,
        crash_vehicle_done=False,
        crash_object_done=False,
        crash_vehicle_penalty=5.0,
        crash_object_penalty=5.0,
        out_of_road_penalty=5.0,
        driving_reward=1.0,
        speed_reward=0.1,
        use_lateral_reward=False,
        daytime=daytime,
        use_render=False,
        disable_expert=True,
        start_seed=0,
        num_scenarios=1000,
    )
    
    # Create wrapper that cycles through hard seeds
    # Each subprocess env gets its own seed counter starting at env_id
    class HardSeedSubprocEnv(FakeHumanEnv):
        """Wrapper that cycles through hard seeds for this subprocess."""
        def __init__(self, config, env_id, seeds):
            super().__init__(config)
            self.hard_seeds = seeds
            self.env_id = env_id
            # Start at different offset for each env to avoid all using same seed
            self.seed_idx = env_id
            self.seeds_used = []
        
        def reset(self, **kwargs):
            seed = self.hard_seeds[self.seed_idx % len(self.hard_seeds)]
            self.seed_idx += 1
            kwargs['seed'] = seed
            self.seeds_used.append(seed)
            return super().reset(**kwargs)
    
    env = HardSeedSubprocEnv(config=env_config, env_id=env_id, seeds=hard_seeds)
    env = Monitor(env=env)
    return env


def create_rollout_envs(num_envs=20, daytime="06:10", force_no_cuda_image=False):
    """
    Create N parallel rollout environments for online evaluation.
    Uses SubprocVecEnv for N>1 (MetaDrive only allows one engine per process).
    Uses DummyVecEnv for N=1 (simpler, no subprocess overhead).
    
    Args:
        num_envs: Number of parallel environments
        daytime: Daytime setting for the environment
        force_no_cuda_image: If True, disable CUDA image even if cupy is available
    
    Returns:
        vec_env: VecEnv with N environments
        seeds_hash: Hash of the seeds for verification
        actual_env_config: Actual config values read from the environment
        use_cuda_image: Whether CUDA image acceleration is enabled
        num_envs: Number of environments (for reference)
    """
    from pvp.sb3.common.vec_env import SubprocVecEnv, DummyVecEnv
    from functools import partial
    
    # Compute seeds hash for verification
    seeds_str = ','.join(map(str, sorted(HARD_200_SEEDS)))
    seeds_hash = hashlib.md5(seeds_str.encode()).hexdigest()[:16]
    
    # image_on_cuda is always False for parallel envs (multiprocessing limitation)
    use_cuda_image = False
    
    if num_envs == 1:
        # For N=1, use DummyVecEnv (simpler, no subprocess overhead)
        def make_single_env():
            return _make_rollout_env_subprocess(0, daytime, HARD_200_SEEDS)
        vec_env = DummyVecEnv([make_single_env])
    else:
        # For N>1, use SubprocVecEnv (each env in separate subprocess)
        # Use partial to bind arguments for pickle compatibility
        env_fns = [partial(_make_rollout_env_subprocess, i, daytime, HARD_200_SEEDS) for i in range(num_envs)]
        vec_env = SubprocVecEnv(env_fns)
    
    # Get actual config (need to get from first env, method differs by VecEnv type)
    if num_envs == 1:
        first_env = vec_env.envs[0]
        actual_env_config = {
            'traffic_density': first_env.unwrapped.config.get('traffic_density', 0.06),
            'daytime': first_env.unwrapped.config.get('daytime', daytime),
            'out_of_road_penalty': first_env.unwrapped.config.get('out_of_road_penalty', 5.0),
            'crash_vehicle_penalty': first_env.unwrapped.config.get('crash_vehicle_penalty', 5.0),
            'crash_object_penalty': first_env.unwrapped.config.get('crash_object_penalty', 5.0),
            'driving_reward': first_env.unwrapped.config.get('driving_reward', 1.0),
            'speed_reward': first_env.unwrapped.config.get('speed_reward', 0.1),
            'horizon': first_env.unwrapped.config.get('horizon', 1500),
            'image_on_cuda': use_cuda_image,
            'num_envs': num_envs,
        }
    else:
        # For SubprocVecEnv, we can't easily access individual env configs
        # Use default values (they're the same as what we set in _make_rollout_env_subprocess)
        actual_env_config = {
            'traffic_density': 0.06,  # env default
            'daytime': daytime,
            'out_of_road_penalty': 5.0,
            'crash_vehicle_penalty': 5.0,
            'crash_object_penalty': 5.0,
            'driving_reward': 1.0,
            'speed_reward': 0.1,
            'horizon': 1500,
            'image_on_cuda': use_cuda_image,
            'num_envs': num_envs,
        }
    
    return vec_env, seeds_hash, actual_env_config, use_cuda_image, num_envs


def safe_mean(arr):
    """Compute mean of a list, returning 0 if empty."""
    return np.mean(arr) if len(arr) > 0 else 0.0


def get_memory_usage():
    """Get current memory usage in MB."""
    process = psutil.Process(os.getpid())
    return process.memory_info().rss / 1024 / 1024


class BatchedDataLoader:
    """
    Data loader for batched format.
    Loads one batch file at a time and CACHES it for multiple samples.
    This is CRITICAL for performance - loading npz files is slow!
    """
    
    def __init__(self, data_dir: str, batch_size: int = 1024, device: str = "auto", samples_per_file: int = 20):
        self.data_dir = Path(data_dir)
        self.batches_dir = self.data_dir / "batches"
        self.batch_size = batch_size
        self.samples_per_file = samples_per_file  # How many batches to sample before loading new file
        
        if device == "auto":
            self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        else:
            self.device = torch.device(device)
        
        # Load metadata if exists, otherwise infer from files
        metadata_path = self.data_dir / "metadata.json"
        if metadata_path.exists():
            with open(metadata_path, 'r') as f:
                self.metadata = json.load(f)
            self.transitions_per_file = self.metadata.get('batch_size', 20480)
        else:
            self.metadata = {}
            self.transitions_per_file = 20480  # Default
        
        # List batch files dynamically - support incremental loading
        self.batch_files = []
        self.verified_files = set()  # Files we've verified are complete
        self._rescan_batch_files()
        
        # Don't require files at init - wait for them dynamically
        self.total_transitions = self.num_batch_files * self.transitions_per_file
        self.last_rescan_time = time.time()
        self.rescan_interval = 30  # Rescan every 30 seconds
        
        # Caching for performance
        self.cached_data = None
        self.cached_file_idx = -1
        self.samples_from_current_file = 0
        
        print(f"BatchedDataLoader initialized (dynamic mode):")
        print(f"  Data dir: {self.data_dir}")
        print(f"  Batch files found: {self.num_batch_files}")
        print(f"  Transitions per file: {self.transitions_per_file}")
        print(f"  Total transitions so far: {self.total_transitions}")
        print(f"  Training batch size: {self.batch_size}")
        print(f"  Samples per file (cache reuse): {self.samples_per_file}")
        print(f"  Device: {self.device}")
        print(f"  Rescan interval: {self.rescan_interval}s (will detect new files)")
    
    def _rescan_batch_files(self):
        """Rescan for new batch files and verify they're complete."""
        all_files = sorted(list(self.batches_dir.glob("batch_*.npz")))
        new_verified = []
        
        for f in all_files:
            if f in self.verified_files:
                new_verified.append(f)
                continue
            
            # Try to verify file is complete by loading it
            try:
                # Check file size is reasonable (> 1MB means likely complete)
                if f.stat().st_size < 1_000_000:
                    continue  # Skip small/incomplete files
                
                # Try loading to verify integrity
                data = np.load(f)
                _ = data['obs_image'].shape  # Access data to verify
                data.close()
                
                self.verified_files.add(f)
                new_verified.append(f)
                print(f"  [DataLoader] New batch file verified: {f.name}", flush=True)
            except Exception as e:
                # File is incomplete or corrupted, skip it
                pass
        
        self.batch_files = new_verified
        self.num_batch_files = len(self.batch_files)
        self.total_transitions = self.num_batch_files * self.transitions_per_file
    
    def _load_new_file(self):
        """Load a random batch file into cache."""
        # Periodically rescan for new files
        if time.time() - self.last_rescan_time > self.rescan_interval:
            old_count = self.num_batch_files
            self._rescan_batch_files()
            self.last_rescan_time = time.time()
            if self.num_batch_files > old_count:
                print(f"  [DataLoader] Found {self.num_batch_files - old_count} new files, total: {self.num_batch_files}", flush=True)
        
        # Wait if no files available yet
        while self.num_batch_files == 0:
            print(f"  [DataLoader] Waiting for batch files in {self.batches_dir}...", flush=True)
            time.sleep(10)
            self._rescan_batch_files()
        
        file_idx = np.random.randint(0, self.num_batch_files)
        data = np.load(self.batch_files[file_idx])
        
        self.cached_data = {
            'obs_image': data['obs_image'],
            'obs_state': data['obs_state'],
            'action': data['action'],
            'size': data['size'] if 'size' in data else len(data['obs_image']),
        }
        self.cached_file_idx = file_idx
        self.samples_from_current_file = 0
    
    def sample(self):
        """
        Sample a batch of transitions from cached data.
        Reloads a new file every `samples_per_file` samples.
        """
        # Check if we need to load a new file
        if self.cached_data is None or self.samples_from_current_file >= self.samples_per_file:
            self._load_new_file()
        
        self.samples_from_current_file += 1
        
        # Sample indices from cached file
        file_size = self.cached_data['size']
        indices = np.random.choice(file_size, size=self.batch_size, replace=True)
        
        # Extract samples
        obs_image = torch.as_tensor(
            self.cached_data['obs_image'][indices], 
            device=self.device, dtype=torch.float32
        )
        obs_state = torch.as_tensor(
            self.cached_data['obs_state'][indices], 
            device=self.device, dtype=torch.float32
        )
        actions = torch.as_tensor(
            self.cached_data['action'][indices], 
            device=self.device, dtype=torch.float32
        )
        
        # Combine observations as dict
        observations = {'image': obs_image, 'state': obs_state}
        
        return observations, actions


def main():
    parser = argparse.ArgumentParser(description="Train BC from batched data")
    parser.add_argument("--data_dir", type=str, required=True,
                        help="Directory containing batched data (on GPU03 local disk)")
    parser.add_argument("--log_dir", type=str, default="",
                        help="Directory for logs and checkpoints (on GPU03 local disk)")
    parser.add_argument("--bc_training_steps", type=int, default=10000,
                        help="Total training steps")
    parser.add_argument("--batch_size", type=int, default=1024,
                        help="Batch size for training")
    parser.add_argument("--learning_rate", type=float, default=1e-4,
                        help="Learning rate")
    parser.add_argument("--save_freq", type=int, default=1000,
                        help="Checkpoint save frequency")
    parser.add_argument("--log_freq", type=int, default=100,
                        help="Logging frequency")
    parser.add_argument("--toy", action="store_true",
                        help="Toy mode for testing")
    parser.add_argument("--seed", type=int, default=0,
                        help="Random seed")
    parser.add_argument("--ckpt", type=str, default="",
                        help="Path to initial checkpoint (for resuming training)")
    parser.add_argument("--start_step", type=int, default=0,
                        help="Starting step (for resuming training, e.g., 40000 to continue from 40K)")
    parser.add_argument("--wandb", action="store_true",
                        help="Enable wandb logging")
    parser.add_argument("--wandb_project", type=str, default="bc-hard-seeds",
                        help="Wandb project name")
    parser.add_argument("--wandb_team", type=str, default="victorique",
                        help="Wandb team name")
    parser.add_argument("--exp_name", type=str, default="bc-1M",
                        help="Experiment name")
    parser.add_argument("--daytime", type=str, default="06:10",
                        help="Daytime for rollout env (should match data generation)")
    parser.add_argument("--rollout_log_freq", type=int, default=100,
                        help="How often to log rollout metrics (in training steps)")
    parser.add_argument("--rollout_step_freq", type=int, default=1,
                        help="Do rollout every N training steps (1=every step, 5=every 5 steps)")
    parser.add_argument("--no_rollout", action="store_true",
                        help="Disable online rollout collection")
    parser.add_argument("--no_cuda_image", action="store_true",
                        help="Disable CUDA image acceleration (use numpy instead of cupy)")
    parser.add_argument("--num_rollout_envs", type=int, default=20,
                        help="Number of parallel rollout environments (default=20)")
    args = parser.parse_args()
    
    # Toy mode
    if args.toy:
        print("=" * 80, flush=True)
        print("TOY MODE ENABLED", flush=True)
        print("=" * 80, flush=True)
        args.bc_training_steps = 20
        args.batch_size = 256
        args.save_freq = 5
        args.log_freq = 5
    
    # Set seeds
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    
    # Validate paths
    data_dir = Path(args.data_dir)
    if not data_dir.exists():
        print(f"ERROR: Data directory not found: {data_dir}")
        sys.exit(1)
    
    # Setup log directory (on GPU03 local disk!)
    if args.log_dir:
        log_dir = Path(args.log_dir)
    else:
        log_dir = Path("/data/caihy/bc_training")
    
    from pvp.utils.utils import get_time_str
    import uuid
    trial_name = f"{args.exp_name}_{get_time_str()}_{uuid.uuid4().hex[:8]}"
    trial_dir = log_dir / trial_name
    trial_dir.mkdir(parents=True, exist_ok=True)
    
    print("=" * 80, flush=True)
    print("BC Training from Batched Data", flush=True)
    print("=" * 80, flush=True)
    print(f"Data directory: {data_dir}", flush=True)
    print(f"Log directory: {trial_dir}", flush=True)
    print(f"Training steps: {args.bc_training_steps}", flush=True)
    print(f"Batch size: {args.batch_size}", flush=True)
    print(f"Save freq: {args.save_freq}", flush=True)
    print(f"Initial memory: {get_memory_usage():.1f} MB", flush=True)
    print("=" * 80, flush=True)
    
    # Create data loader
    print("\n[1] Creating data loader...", flush=True)
    data_loader = BatchedDataLoader(str(data_dir), batch_size=args.batch_size)
    print(f"    Memory after data loader: {get_memory_usage():.1f} MB", flush=True)
    
    # Test data loading
    print("\n[2] Testing data loading...", flush=True)
    obs, actions = data_loader.sample()
    print(f"    obs['image'] shape: {obs['image'].shape}", flush=True)
    print(f"    obs['state'] shape: {obs['state'].shape}", flush=True)
    print(f"    actions shape: {actions.shape}", flush=True)
    print(f"    Batch size correct: {actions.shape[0] == args.batch_size}", flush=True)
    print(f"    Memory after sample: {get_memory_usage():.1f} MB", flush=True)
    
    # Create model
    print("\n[3] Creating BC model...", flush=True)
    from pvp.sb3.td3.td3 import TD3
    from pvp.sb3.td3.policies import TD3Policy
    from pvp.sb3.sac.our_features_extractor import OurFeaturesExtractorCNN as OurFeaturesExtractor
    
    # Create a simple dummy observation/action space without loading full metadrive
    import gymnasium as gym
    
    # Match the observation space from data
    obs_space = gym.spaces.Dict({
        'image': gym.spaces.Box(low=0, high=1, shape=(84, 84, 3, 3), dtype=np.float32),
        'state': gym.spaces.Box(low=-np.inf, high=np.inf, shape=(19,), dtype=np.float32),
    })
    action_space = gym.spaces.Box(low=-1, high=1, shape=(2,), dtype=np.float32)
    
    # Create a minimal dummy env wrapper
    class DummyEnv(gym.Env):
        def __init__(self):
            super().__init__()
            self.observation_space = obs_space
            self.action_space = action_space
            self.num_envs = 1
            self.metadata = {'render.modes': []}
        def reset(self, seed=None, options=None):
            return {'image': np.zeros((84, 84, 3, 3), dtype=np.float32), 'state': np.zeros(19, dtype=np.float32)}, {}
        def step(self, action):
            return {'image': np.zeros((84, 84, 3, 3), dtype=np.float32), 'state': np.zeros(19, dtype=np.float32)}, 0.0, False, False, {}
        def render(self):
            pass
        def close(self):
            pass
    
    dummy_env = DummyEnv()
    
    policy_kwargs = dict(
        features_extractor_class=OurFeaturesExtractor,
        features_extractor_kwargs=dict(features_dim=275),
        share_features_extractor=False,
        net_arch=[256,]
    )
    
    model = TD3(
        policy=TD3Policy,
        env=dummy_env,
        learning_rate=args.learning_rate,
        buffer_size=1000,
        batch_size=args.batch_size,
        tau=0.005,
        gamma=0.99,
        train_freq=1,
        gradient_steps=1,
        policy_delay=2,
        tensorboard_log=str(trial_dir),
        verbose=2,
        seed=args.seed,
        device="auto",
        policy_kwargs=policy_kwargs,
        use_td3_bc=False,
        bc_loss_weight=1.0,
    )
    
    dummy_env.close()
    print(f"    Model device: {model.device}", flush=True)
    print(f"    Memory after model: {get_memory_usage():.1f} MB", flush=True)
    
    # Load initial checkpoint
    print("\n[4] Loading initial checkpoint...", flush=True)
    script_dir = Path(os.path.dirname(os.path.abspath(__file__)))
    if args.ckpt:
        ckpt_path = Path(args.ckpt)
    else:
        ckpt_path = script_dir / "domainAexpertBC.zip"
    
    if ckpt_path.exists():
        print(f"    Loading from: {ckpt_path}", flush=True)
        from pvp.sb3.common.save_util import load_from_zip_file
        data, params, pytorch_variables = load_from_zip_file(ckpt_path, device=model.device, print_system_info=False)
        model.set_parameters(params, exact_match=False, device=model.device)
        print(f"    Checkpoint loaded!", flush=True)
    else:
        print(f"    WARNING: Checkpoint not found: {ckpt_path}", flush=True)
    
    print(f"    Memory after checkpoint: {get_memory_usage():.1f} MB", flush=True)
    
    # Initialize wandb
    wandb_run = None
    if args.wandb:
        print("\n[5] Initializing wandb...", flush=True)
        try:
            import wandb as wandb_module
            wandb_run = wandb_module.init(
                project=args.wandb_project,
                entity=args.wandb_team,
                name=trial_name,
                config=vars(args),
            )
            print("    Wandb initialized!", flush=True)
        except Exception as e:
            print(f"    WARNING: Failed to initialize wandb: {e}", flush=True)
            args.wandb = False
    
    # Create rollout environments for online evaluation (N parallel envs)
    rollout_env = None
    rollout_obs = None
    ep_info_buffer = deque(maxlen=100)  # Store recent episode infos
    ep_extended_buffer = deque(maxlen=100)  # Store extended metrics (success_no_bad, etc.)
    rollout_seeds_hash = None
    actual_rollout_config = None
    rollout_num_envs = args.num_rollout_envs
    
    # Rollout episode-level tracking - now arrays for N parallel envs
    rollout_episode_count = 0  # Total episodes completed across all envs
    rollout_step_in_episode = None  # Will be np.zeros(N)
    rollout_had_crash_vehicle = None  # Will be np.zeros(N, dtype=bool)
    rollout_had_crash_object = None
    rollout_had_out_of_road = None
    rollout_had_bad_event = None
    rollout_arrive_dest = None
    rollout_route_completion = None  # Will be np.zeros(N)
    rollout_total_crash_penalty = None
    rollout_total_out_of_road_penalty = None
    rollout_total_velocity = None
    rollout_min_vehicle_distance = None
    rollout_close_encounters = None
    rollout_safe_passes = None
    rollout_dangerous_close = None
    rollout_current_seed = None  # Will be np.zeros(N, dtype=object)
    
    rollout_image_on_cuda = False  # Track if using CUDA image acceleration
    
    def init_rollout_tracking_arrays(n_envs):
        """Initialize per-env tracking arrays."""
        return {
            'step_in_episode': np.zeros(n_envs, dtype=np.int32),
            'had_crash_vehicle': np.zeros(n_envs, dtype=np.bool_),
            'had_crash_object': np.zeros(n_envs, dtype=np.bool_),
            'had_out_of_road': np.zeros(n_envs, dtype=np.bool_),
            'had_bad_event': np.zeros(n_envs, dtype=np.bool_),
            'arrive_dest': np.zeros(n_envs, dtype=np.bool_),
            'route_completion': np.zeros(n_envs, dtype=np.float32),
            'route_at_first_bad': np.full(n_envs, -1.0, dtype=np.float32),  # -1 means no bad event yet
            'total_crash_penalty': np.zeros(n_envs, dtype=np.float32),
            'total_out_of_road_penalty': np.zeros(n_envs, dtype=np.float32),
            'total_velocity': np.zeros(n_envs, dtype=np.float32),
            'min_vehicle_distance': np.full(n_envs, float('inf'), dtype=np.float32),
            'close_encounters': np.zeros(n_envs, dtype=np.int32),
            'safe_passes': np.zeros(n_envs, dtype=np.int32),
            'dangerous_close': np.zeros(n_envs, dtype=np.int32),
            'current_seed': np.zeros(n_envs, dtype=np.int32),
        }
    
    def reset_env_tracking(tracking, env_idx):
        """Reset tracking for a single env after episode end."""
        tracking['step_in_episode'][env_idx] = 0
        tracking['had_crash_vehicle'][env_idx] = False
        tracking['had_crash_object'][env_idx] = False
        tracking['had_out_of_road'][env_idx] = False
        tracking['had_bad_event'][env_idx] = False
        tracking['arrive_dest'][env_idx] = False
        tracking['route_completion'][env_idx] = 0.0
        tracking['route_at_first_bad'][env_idx] = -1.0  # -1 means no bad event yet
        tracking['total_crash_penalty'][env_idx] = 0.0
        tracking['total_out_of_road_penalty'][env_idx] = 0.0
        tracking['total_velocity'][env_idx] = 0.0
        tracking['min_vehicle_distance'][env_idx] = float('inf')
        tracking['close_encounters'][env_idx] = 0
        tracking['safe_passes'][env_idx] = 0
        tracking['dangerous_close'][env_idx] = 0
        tracking['current_seed'][env_idx] = 0
    
    rollout_tracking = None  # Will be initialized after env creation
    
    if not args.no_rollout:
        print(f"\n[6] Creating {rollout_num_envs} parallel rollout environments...", flush=True)
        try:
            rollout_env, rollout_seeds_hash, actual_rollout_config, rollout_image_on_cuda, rollout_num_envs = create_rollout_envs(
                num_envs=rollout_num_envs,
                daytime=args.daytime, 
                force_no_cuda_image=args.no_cuda_image
            )
            # DummyVecEnv.reset() returns stacked obs: {'image': (N, H, W, C, S), 'state': (N, D)}
            rollout_obs = rollout_env.reset()
            
            # Initialize per-env tracking arrays
            rollout_tracking = init_rollout_tracking_arrays(rollout_num_envs)
            
            print(f"    Rollout envs created: {rollout_num_envs} parallel environments!", flush=True)
            print(f"    Seeds hash: {rollout_seeds_hash}", flush=True)
            print(f"    image_on_cuda: {rollout_image_on_cuda} (cupy available: {_cupy_available})", flush=True)
            print(f"    Obs shapes: image={rollout_obs['image'].shape}, state={rollout_obs['state'].shape}", flush=True)
            print(f"    Actual env config:", flush=True)
            for k, v in actual_rollout_config.items():
                print(f"      {k}: {v}", flush=True)
            
            # Log env config to wandb
            if args.wandb and wandb_run:
                daytime_numeric = int(args.daytime.replace(":", "")) if args.daytime else 0
                env_cfg_metrics = {
                    'env_cfg/traffic_density': actual_rollout_config['traffic_density'],
                    'env_cfg/daytime_numeric': daytime_numeric,
                    'env_cfg/out_of_road_penalty': actual_rollout_config['out_of_road_penalty'],
                    'env_cfg/crash_vehicle_penalty': actual_rollout_config['crash_vehicle_penalty'],
                    'env_cfg/crash_object_penalty': actual_rollout_config['crash_object_penalty'],
                    'env_cfg/driving_reward': actual_rollout_config['driving_reward'],
                    'env_cfg/speed_reward': actual_rollout_config['speed_reward'],
                    'env_cfg/horizon': actual_rollout_config['horizon'],
                    'env_cfg/num_seeds': len(HARD_200_SEEDS),
                    'env_cfg/seeds_hash_numeric': int(rollout_seeds_hash[:8], 16) % 1000000,
                    'env_cfg/num_rollout_envs': rollout_num_envs,
                }
                wandb_run.log(env_cfg_metrics)
                wandb_run.summary['seeds_hash'] = rollout_seeds_hash
                wandb_run.summary['daytime'] = args.daytime
                wandb_run.summary['traffic_density'] = actual_rollout_config['traffic_density']
                wandb_run.summary['num_rollout_envs'] = rollout_num_envs
                print(f"    Logged env_cfg to wandb!", flush=True)
        except Exception as e:
            print(f"    WARNING: Failed to create rollout envs: {e}", flush=True)
            import traceback
            traceback.print_exc()
            rollout_env = None
    else:
        print("\n[6] Rollout collection disabled (--no_rollout)", flush=True)
    
    # Training loop
    print("\n" + "=" * 80, flush=True)
    print("Starting BC Training Loop", flush=True)
    print("=" * 80, flush=True)
    
    from pvp.sb3.common.utils import polyak_update
    
    start_time = time.time()
    total_loss = 0
    memory_samples = []
    log_freq = args.log_freq
    start_step = args.start_step
    total_steps = args.bc_training_steps
    
    if start_step > 0:
        print(f"\n[7] RESUMING from step {start_step}...", flush=True)
        print(f"    Training steps: {start_step + 1} to {total_steps}", flush=True)
    
    # Accumulators for averaging
    loss_acc = []
    steering_loss_acc = []
    accel_loss_acc = []
    
    for step in range(start_step + 1, total_steps + 1):
        # Sample batch
        obs, actions = data_loader.sample()
        
        # Forward pass
        model.actor.train()
        predicted_actions = model.actor(obs)
        
        # BC loss (total)
        bc_loss = torch.nn.functional.mse_loss(predicted_actions, actions)
        
        # Per-dimension losses
        bc_loss_steering = torch.nn.functional.mse_loss(predicted_actions[:, 0], actions[:, 0])
        bc_loss_accel = torch.nn.functional.mse_loss(predicted_actions[:, 1], actions[:, 1])
        
        # Backward pass
        model.actor.optimizer.zero_grad()
        bc_loss.backward()
        
        # Gradient norm (before clipping)
        grad_norm = 0.0
        for p in model.actor.parameters():
            if p.grad is not None:
                grad_norm += p.grad.data.norm(2).item() ** 2
        grad_norm = grad_norm ** 0.5
        
        model.actor.optimizer.step()
        
        # Update target network
        if step % model.policy_delay == 0:
            polyak_update(model.actor.parameters(), model.actor_target.parameters(), model.tau)
        
        # Accumulate for averaging
        loss_acc.append(bc_loss.item())
        steering_loss_acc.append(bc_loss_steering.item())
        accel_loss_acc.append(bc_loss_accel.item())
        model._n_updates += 1
        
        # ============ ONLINE ROLLOUT COLLECTION (N PARALLEL ENVS) ============
        # Collect one step of rollout data from N parallel envs using current policy
        # Only do rollout every N steps for speedup
        if rollout_env is not None and rollout_obs is not None and rollout_tracking is not None and step % args.rollout_step_freq == 0:
            # Increment step counter for all envs
            rollout_tracking['step_in_episode'] += 1
            
            with torch.no_grad():
                # Convert observation to tensor - NOW BATCHED (N, H, W, C, S)
                # DummyVecEnv stacks observations: obs['image'] is (N, 84, 84, 3, 3)
                if rollout_image_on_cuda and _cupy_available:
                    # For DummyVecEnv with cupy, obs is already stacked numpy (DummyVecEnv converts)
                    # If individual envs return cupy, DummyVecEnv may convert to numpy during stacking
                    # Check if still cupy array
                    if hasattr(rollout_obs['image'], 'toDlpack'):
                        image_tensor = from_dlpack(rollout_obs['image'].toDlpack())
                    else:
                        image_tensor = torch.as_tensor(rollout_obs['image'], device=model.device)
                    if image_tensor.dtype == torch.uint8:
                        image_tensor = image_tensor.float() / 255.0
                    else:
                        image_tensor = image_tensor.float()
                    rollout_obs_tensor = {
                        'image': image_tensor,  # Already (N, H, W, C, S)
                        'state': torch.as_tensor(rollout_obs['state'], device=model.device, dtype=torch.float32),
                    }
                else:
                    # Standard numpy -> torch conversion for batched obs
                    rollout_obs_tensor = {
                        'image': torch.as_tensor(rollout_obs['image'], device=model.device, dtype=torch.float32),
                        'state': torch.as_tensor(rollout_obs['state'], device=model.device, dtype=torch.float32),
                    }
                # Get actions from policy for all N envs - returns (N, 2)
                policy_actions = model.actor(rollout_obs_tensor).cpu().numpy()  # (N, 2)
            
            # Step all N environments with their respective actions
            # VecEnv.step returns: obs, rewards (N,), dones (N,), infos (list of N dicts)
            new_obs, rewards, dones, infos = rollout_env.step(policy_actions)
            
            # === PER-ENV METRIC TRACKING ===
            for i in range(rollout_num_envs):
                info = infos[i]
                
                # Get current seed on first step of episode for this env
                if rollout_tracking['step_in_episode'][i] == 1:
                    rollout_tracking['current_seed'][i] = info.get('env_seed', 0)
                
                # Track velocity for this env
                velocity = info.get('velocity', 0.0)
                if isinstance(velocity, (list, np.ndarray)):
                    velocity = np.linalg.norm(velocity)
                rollout_tracking['total_velocity'][i] += velocity
                
                # Track crash events for this env
                if info.get('crash_vehicle', False):
                    rollout_tracking['had_crash_vehicle'][i] = True
                    rollout_tracking['total_crash_penalty'][i] += 5.0
                if info.get('crash_object', False):
                    rollout_tracking['had_crash_object'][i] = True
                    rollout_tracking['total_crash_penalty'][i] += 5.0
                if info.get('out_of_road', False):
                    rollout_tracking['had_out_of_road'][i] = True
                    rollout_tracking['total_out_of_road_penalty'][i] += 5.0
                
                # Track bad event for this env - record route at FIRST bad event
                if rollout_tracking['had_crash_vehicle'][i] or rollout_tracking['had_crash_object'][i] or rollout_tracking['had_out_of_road'][i]:
                    if not rollout_tracking['had_bad_event'][i]:
                        # First bad event - record route completion at this moment
                        rollout_tracking['route_at_first_bad'][i] = info.get('route_completion', 0.0)
                    rollout_tracking['had_bad_event'][i] = True
                
                # Track success for this env
                if info.get('arrive_dest', False):
                    rollout_tracking['arrive_dest'][i] = True
                
                # Track route completion for this env
                rollout_tracking['route_completion'][i] = max(
                    rollout_tracking['route_completion'][i], 
                    info.get('route_completion', 0.0)
                )
                
                # Track traffic proximity for this env
                min_dist = info.get('min_vehicle_distance', float('inf'))
                if min_dist < float('inf'):
                    rollout_tracking['min_vehicle_distance'][i] = min(
                        rollout_tracking['min_vehicle_distance'][i], min_dist
                    )
                if min_dist < 5.0:  # Close encounter threshold
                    rollout_tracking['close_encounters'][i] += 1
                    step_crash = info.get('crash_vehicle', False) or info.get('crash_object', False)
                    if step_crash:
                        rollout_tracking['dangerous_close'][i] += 1
                    else:
                        rollout_tracking['safe_passes'][i] += 1
                
                # === EPISODE END FOR ENV i ===
                if dones[i]:
                    rollout_episode_count += 1
                    
                    # Compute extended metrics for this env
                    step_count = rollout_tracking['step_in_episode'][i]
                    success_no_bad = rollout_tracking['arrive_dest'][i] and not rollout_tracking['had_bad_event'][i]
                    rc_no_bad = rollout_tracking['route_completion'][i] if not rollout_tracking['had_bad_event'][i] else 0.0
                    # Route until first bad event (or full route if no bad event)
                    route_at_bad = rollout_tracking['route_at_first_bad'][i]
                    route_until_bad = route_at_bad if route_at_bad >= 0 else rollout_tracking['route_completion'][i]
                    avg_velocity = rollout_tracking['total_velocity'][i] / step_count if step_count > 0 else 0.0
                    close_enc = rollout_tracking['close_encounters'][i]
                    safe_pass_rate = rollout_tracking['safe_passes'][i] / close_enc if close_enc > 0 else 1.0
                    close_enc_crash_rate = rollout_tracking['dangerous_close'][i] / close_enc if close_enc > 0 else 0.0
                    
                    # Store basic ep_info from Monitor (VecEnv stores it in 'episode' key)
                    if 'episode' in info:
                        ep_info_buffer.append(info['episode'])
                    
                    # Store extended metrics
                    ep_extended = {
                        'seed': int(rollout_tracking['current_seed'][i]),
                        'success_no_bad': float(success_no_bad),
                        'success_rate': float(rollout_tracking['arrive_dest'][i]),
                        'route_completion': float(rollout_tracking['route_completion'][i]),
                        'route_completion_no_bad': float(rc_no_bad),
                        'route_until_bad': float(route_until_bad),  # Route at first bad event (or full if no bad)
                        'crash_vehicle_rate': float(rollout_tracking['had_crash_vehicle'][i]),
                        'crash_object_rate': float(rollout_tracking['had_crash_object'][i]),
                        'out_of_road_rate': float(rollout_tracking['had_out_of_road'][i]),
                        'any_bad_event_rate': float(rollout_tracking['had_bad_event'][i]),
                        'crash_penalty': float(rollout_tracking['total_crash_penalty'][i]),
                        'out_of_road_penalty': float(rollout_tracking['total_out_of_road_penalty'][i]),
                        'avg_velocity': float(avg_velocity),
                        'min_vehicle_distance': float(rollout_tracking['min_vehicle_distance'][i]) if rollout_tracking['min_vehicle_distance'][i] < float('inf') else -1,
                        'close_encounters': int(rollout_tracking['close_encounters'][i]),
                        'safe_passes': int(rollout_tracking['safe_passes'][i]),
                        'dangerous_close': int(rollout_tracking['dangerous_close'][i]),
                        'safe_pass_rate': float(safe_pass_rate),
                        'close_enc_crash_rate': float(close_enc_crash_rate),
                        'episode_length': int(step_count),
                        'env_id': i,
                    }
                    ep_extended_buffer.append(ep_extended)
                    
                    # Reset tracking for this env only (VecEnv auto-resets)
                    reset_env_tracking(rollout_tracking, i)
                    
                    # Verification print for first few episodes
                    if rollout_episode_count <= 5:
                        print(f"[Rollout] Ep={rollout_episode_count} env={i} seed={ep_extended['seed']} "
                              f"success_no_bad={ep_extended['success_no_bad']:.0f} "
                              f"route={ep_extended['route_completion']:.2f} "
                              f"route_until_bad={ep_extended['route_until_bad']:.2f} "
                              f"len={ep_extended['episode_length']}", flush=True)
            
            # Update obs for next step (VecEnv already auto-reset finished envs)
            rollout_obs = new_obs
        # ====================================================
        
        # Memory tracking
        current_memory = get_memory_usage()
        memory_samples.append(current_memory)
        
        # Logging
        if step % log_freq == 0 or step == start_step + 1:
            elapsed = time.time() - start_time
            steps_done = step - start_step
            rate = steps_done / elapsed if elapsed > 0 else 0
            steps_remaining = total_steps - step
            eta_seconds = steps_remaining / rate if rate > 0 else 0
            eta_hours = eta_seconds / 3600
            
            avg_loss = np.mean(loss_acc[-log_freq:]) if loss_acc else 0
            avg_steering_loss = np.mean(steering_loss_acc[-log_freq:]) if steering_loss_acc else 0
            avg_accel_loss = np.mean(accel_loss_acc[-log_freq:]) if accel_loss_acc else 0
            
            log_msg = f"[{step}/{total_steps}] Loss: {avg_loss:.4f} (steer: {avg_steering_loss:.4f}, accel: {avg_accel_loss:.4f}), Mem: {current_memory:.0f}MB, Rate: {rate:.1f}/s, ETA: {eta_hours:.1f}h"
            print(log_msg, flush=True)
            
            if args.wandb and wandb_run:
                # Compute detailed action statistics
                with torch.no_grad():
                    data_steering = actions[:, 0]
                    data_accel = actions[:, 1]
                    policy_steering = predicted_actions[:, 0]
                    policy_accel = predicted_actions[:, 1]
                    action_diff_l2 = torch.norm(predicted_actions - actions, dim=1).mean().item()
                
                log_dict = {
                    # Loss metrics
                    'train/bc_loss': avg_loss,
                    'train/bc_loss_steering': avg_steering_loss,
                    'train/bc_loss_accel': avg_accel_loss,
                    'train/grad_norm': grad_norm,
                    
                    # Data action statistics
                    'train/data_mean_steering': data_steering.mean().item(),
                    'train/data_mean_steering_abs': torch.abs(data_steering).mean().item(),
                    'train/data_mean_accel': data_accel.mean().item(),
                    'train/data_mean_accel_abs': torch.abs(data_accel).mean().item(),
                    'train/data_std_steering': data_steering.std().item(),
                    'train/data_std_accel': data_accel.std().item(),
                    
                    # Policy action statistics
                    'train/policy_mean_steering': policy_steering.mean().item(),
                    'train/policy_mean_steering_abs': torch.abs(policy_steering).mean().item(),
                    'train/policy_mean_accel': policy_accel.mean().item(),
                    'train/policy_mean_accel_abs': torch.abs(policy_accel).mean().item(),
                    'train/policy_std_steering': policy_steering.std().item(),
                    'train/policy_std_accel': policy_accel.std().item(),
                    
                    # Action difference
                    'train/action_diff_l2': action_diff_l2,
                    
                    # Training stats
                    'train/n_updates': model._n_updates,
                    'train/learning_rate': args.learning_rate,
                    'train/memory_mb': current_memory,
                    'train/step': step,
                    'train/rate_per_sec': rate,
                    'train/eta_hours': eta_hours,
                }
                
                # ============ ROLLOUT METRICS (ENHANCED) ============
                # Log rollout metrics from ep_info_buffer + ep_extended_buffer
                if len(ep_info_buffer) > 0 and step % args.rollout_log_freq == 0:
                    # Core metrics from Monitor
                    log_dict['rollout/ep_rew_mean'] = safe_mean([ep_info["r"] for ep_info in ep_info_buffer])
                    log_dict['rollout/ep_len_mean'] = safe_mean([ep_info["l"] for ep_info in ep_info_buffer])
                    
                    # Log ALL environment-specific metrics from Monitor (same as _dump_logs)
                    first_ep_info = ep_info_buffer[-1]
                    for k, v in first_ep_info.items():
                        if k not in ["r", "l"] and type(v) is not str:
                            try:
                                log_dict["rollout/{}_mean".format(k)] = safe_mean(
                                    [ep_info[k] for ep_info in ep_info_buffer if k in ep_info]
                                )
                            except (TypeError, ValueError, KeyError):
                                pass
                    
                    # Also log "total_*" as sums
                    for k, v in first_ep_info.items():
                        if k.startswith("total"):
                            log_dict["rollout/{}_sum".format(k)] = ep_info_buffer[-1].get(k, 0)
                    
                    # ======== EXTENDED METRICS from ep_extended_buffer ========
                    if len(ep_extended_buffer) > 0:
                        # Success metrics
                        log_dict['rollout/success_no_bad'] = safe_mean([ep['success_no_bad'] for ep in ep_extended_buffer])
                        log_dict['rollout/success_rate'] = safe_mean([ep['success_rate'] for ep in ep_extended_buffer])
                        
                        # Route completion metrics
                        log_dict['rollout/route_completion_no_bad'] = safe_mean([ep['route_completion_no_bad'] for ep in ep_extended_buffer])
                        log_dict['rollout/route_until_bad'] = safe_mean([ep['route_until_bad'] for ep in ep_extended_buffer])
                        log_dict['rollout/route_completion'] = safe_mean([ep['route_completion'] for ep in ep_extended_buffer])
                        
                        # Safety metrics
                        log_dict['rollout/crash_vehicle_rate'] = safe_mean([ep['crash_vehicle_rate'] for ep in ep_extended_buffer])
                        log_dict['rollout/crash_object_rate'] = safe_mean([ep['crash_object_rate'] for ep in ep_extended_buffer])
                        log_dict['rollout/out_of_road_rate'] = safe_mean([ep['out_of_road_rate'] for ep in ep_extended_buffer])
                        log_dict['rollout/any_bad_event_rate'] = safe_mean([ep['any_bad_event_rate'] for ep in ep_extended_buffer])
                        
                        # Reward decomposition
                        log_dict['rollout/crash_penalty_mean'] = safe_mean([ep['crash_penalty'] for ep in ep_extended_buffer])
                        log_dict['rollout/out_of_road_penalty_mean'] = safe_mean([ep['out_of_road_penalty'] for ep in ep_extended_buffer])
                        log_dict['rollout/avg_velocity_mean'] = safe_mean([ep['avg_velocity'] for ep in ep_extended_buffer])
                        
                        # Traffic proximity
                        min_dists = [ep['min_vehicle_distance'] for ep in ep_extended_buffer if ep['min_vehicle_distance'] > 0]
                        log_dict['rollout/min_vehicle_distance'] = safe_mean(min_dists) if min_dists else -1
                        log_dict['rollout/close_encounters_mean'] = safe_mean([ep['close_encounters'] for ep in ep_extended_buffer])
                        log_dict['rollout/safe_pass_rate'] = safe_mean([ep['safe_pass_rate'] for ep in ep_extended_buffer])
                        log_dict['rollout/close_enc_crash_rate'] = safe_mean([ep['close_enc_crash_rate'] for ep in ep_extended_buffer])
                        
                        # Difficulty segment analysis (if enough episodes)
                        if len(ep_extended_buffer) >= 5:
                            # Sort by seed to analyze by difficulty (lower seeds = harder in HARD_200_SEEDS)
                            sorted_eps = sorted([ep for ep in ep_extended_buffer if ep['seed'] is not None], 
                                               key=lambda x: HARD_200_SEEDS.index(x['seed']) if x['seed'] in HARD_200_SEEDS else 999)
                            if len(sorted_eps) >= 5:
                                num_per_seg = len(sorted_eps) // 5
                                segments = ['hardest', 'hard', 'medium', 'easy', 'easiest']
                                for seg_idx, seg_name in enumerate(segments):
                                    start_idx = seg_idx * num_per_seg
                                    end_idx = min(start_idx + num_per_seg, len(sorted_eps))
                                    if start_idx < len(sorted_eps):
                                        seg_eps = sorted_eps[start_idx:end_idx]
                                        log_dict[f'rollout/segment_{seg_name}_success'] = safe_mean([ep['success_rate'] for ep in seg_eps])
                                        log_dict[f'rollout/segment_{seg_name}_crash'] = safe_mean([ep['crash_vehicle_rate'] for ep in seg_eps])
                    # ===========================================================
                    
                    # Print rollout summary (enhanced)
                    if step % (args.rollout_log_freq * 5) == 0:
                        succ_no_bad = log_dict.get('rollout/success_no_bad', 0)
                        rc_no_bad = log_dict.get('rollout/route_completion_no_bad', 0)
                        route_until_bad = log_dict.get('rollout/route_until_bad', 0)
                        route_comp = log_dict.get('rollout/route_completion', 0)
                        crash = log_dict.get('rollout/crash_vehicle_rate', 0)
                        out_road = log_dict.get('rollout/out_of_road_rate', 0)
                        crash_pen = log_dict.get('rollout/crash_penalty_mean', 0)
                        safe_pass = log_dict.get('rollout/safe_pass_rate', 0)
                        print(f"    [Rollout] Ep={len(ep_extended_buffer)} R={log_dict.get('rollout/ep_rew_mean', 0):.1f} RC={route_comp*100:.0f}% RCUntilBad={route_until_bad*100:.0f}% "
                              f"SuccNoBad={succ_no_bad:.0%} RCNoBad={rc_no_bad:.0%} "
                              f"Crash={crash:.0%} OoR={out_road:.0%} CrashPen={crash_pen:.1f} SafePass={safe_pass:.0%}", flush=True)
                # =========================================
                
                wandb_run.log(log_dict, step=step)
        
        # Save checkpoint
        if step % args.save_freq == 0:
            ckpt_path = trial_dir / f"bc_step_{step:06d}.zip"
            model.save(str(ckpt_path))
            print(f"    [SAVE] Checkpoint saved: {ckpt_path}", flush=True)
            
            # Verify checkpoint is on local disk
            if str(ckpt_path).startswith("/data/"):
                print(f"    [OK] Checkpoint on local disk (GPU03)", flush=True)
            else:
                print(f"    [WARNING] Checkpoint NOT on local disk!", flush=True)
    
    # Final save
    final_path = trial_dir / "bc_final.zip"
    model.save(str(final_path))
    print(f"\n[FINAL] Saved: {final_path}", flush=True)
    
    # Memory leak check
    print("\n" + "=" * 80, flush=True)
    print("Memory Leak Check", flush=True)
    print("=" * 80, flush=True)
    
    if len(memory_samples) > 10:
        first_10 = np.mean(memory_samples[:10])
        last_10 = np.mean(memory_samples[-10:])
        memory_growth = last_10 - first_10
        
        print(f"    First 10 steps avg: {first_10:.1f} MB", flush=True)
        print(f"    Last 10 steps avg: {last_10:.1f} MB", flush=True)
        print(f"    Memory growth: {memory_growth:.1f} MB", flush=True)
        
        if memory_growth > 500:
            print(f"    [WARNING] Possible memory leak detected!", flush=True)
        else:
            print(f"    [OK] No significant memory leak", flush=True)
    
    # Summary
    print("\n" + "=" * 80, flush=True)
    print("Training Summary", flush=True)
    print("=" * 80, flush=True)
    print(f"    Start step: {start_step}", flush=True)
    print(f"    End step: {total_steps}", flush=True)
    print(f"    Steps trained this run: {total_steps - start_step}", flush=True)
    print(f"    Total updates: {model._n_updates}", flush=True)
    print(f"    Training time: {(time.time() - start_time)/60:.1f} min", flush=True)
    print(f"    Final memory: {get_memory_usage():.1f} MB", flush=True)
    print(f"    Checkpoints saved to: {trial_dir}", flush=True)
    print("=" * 80, flush=True)
    
    # Verify all checkpoints
    print("\n[VERIFY] Checking saved checkpoints...", flush=True)
    saved_ckpts = list(trial_dir.glob("*.zip"))
    print(f"    Found {len(saved_ckpts)} checkpoints", flush=True)
    for ckpt in saved_ckpts[:5]:
        print(f"      - {ckpt.name} ({os.path.getsize(ckpt)/1024/1024:.1f} MB)", flush=True)
    
    # Cleanup rollout env
    if rollout_env is not None:
        print("\n[CLEANUP] Closing rollout environment...", flush=True)
        rollout_env.close()
        print("    Rollout env closed!", flush=True)
    
    if args.wandb and wandb_run:
        wandb_run.finish()


if __name__ == "__main__":
    main()
